function [F,Updated] = Update_Conventional_stFI_Explicit(F,cdt,MeshParam,MeshFaceAreas,Updated)

cdt_subgrid=cdt/MeshParam.UpdateNum_subgrid;

[F]=Update_E_CoarseRegion(F,cdt,MeshParam,MeshFaceAreas);
MeshFaceAreas.Bz_innercorner    = MeshFaceAreas.Bz_innercorner_Initial;
MeshFaceAreas.Bz_insideboundary = MeshFaceAreas.Bz_insideboundary_Initial;
[F,Updated]=Update_E_RegionBoundary_FirstTimeSec(F,cdt,cdt_subgrid,MeshParam,MeshFaceAreas,Updated);
[F]=Update_E_FineRegion(F,cdt_subgrid,MeshParam);
[F]=Update_Bz_FineRegion(F,MeshParam);
for TimeSec=2:MeshParam.UpdateNum_subgrid
    MeshFaceAreas.Bz_innercorner    = MeshFaceAreas.Bz_innercorner_HemiStep;
    MeshFaceAreas.Bz_insideboundary = MeshFaceAreas.Bz_insideboundary_HemiStep;
    [F]=Update_E_RegionBoundary_NotFirstTimeSec(F,cdt_subgrid,MeshParam,MeshFaceAreas);   
    [F]=Update_E_FineRegion(F,cdt_subgrid,MeshParam);
    [F]=Update_Bz_FineRegion(F,MeshParam);
end
[F,Updated]=Update_Bz_CoarseRegion(F,MeshParam,Updated);
end

%%
function [F]=Update_E_CoarseRegion(F,cdt,MeshParam,MeshFaceAreas)

%% update Ex
j=1;
for i=1:MeshParam.Size_X
   % Updated(i,j)=Updated(i,j)+1;
    F(i,j).Ex=((1.0*cdt)/1.0)*( ...
        (1.0/(1.0*cdt))*F(i,j).Ex ...
        +(cdt/1.0)*F(i,j).Bz ...
        -(cdt/1.0)*F(i,MeshParam.Size_Y).Bz...
        );
end
for j=2:MeshParam.Fine_Y_from-2
    for i=1:MeshParam.Size_X
           % Updated(i,j)=Updated(i,j)+1;
        F(i,j).Ex=((1.0*cdt)/1.0)*( ...
            (1.0/(1.0*cdt))*F(i,j).Ex ...
            +(cdt/1.0)*F(i,j).Bz ...
            -(cdt/1.0)*F(i,j-1).Bz...
            );
    end
end

for j=MeshParam.Fine_Y_from-1:MeshParam.Fine_Y_to+2
    for i=1:MeshParam.Fine_X_from-2
           % Updated(i,j)=Updated(i,j)+1;
        F(i,j).Ex=((1.0*cdt)/1.0)*( ...
            (1.0/(1.0*cdt))*F(i,j).Ex ...
            +(cdt/1.0)*F(i,j).Bz ...
            -(cdt/1.0)*F(i,j-1).Bz...
            );
    end
end
j=MeshParam.Fine_Y_from-1;
for i=MeshParam.Fine_X_from-1:...
        (MeshParam.Fine_X_to+1)-(MeshParam.Fine_X_from-1):...
        MeshParam.Fine_X_to+1
     % Updated(i,j)=Updated(i,j)+1;
    F(i,j).Ex=...
        ((1.0*cdt)/1.0)*( ...
        (1.0/(1.0*cdt))*F(i,j).Ex ...
        +(cdt/MeshFaceAreas.Bz_outercorner)*F(i,j  ).Bz ...
        -(cdt/1.0                )*F(i,j-1).Bz...
        );
end
for i=MeshParam.Fine_X_from:...
        MeshParam.Fine_X_to-MeshParam.Fine_X_from:...
        MeshParam.Fine_X_to
       % Updated(i,j)=Updated(i,j)+1;
    F(i,j).Ex=...
        ((1.0*cdt)/1.0)*( ...
        (1.0/(1.0*cdt))*F(i,j).Ex ...
        +(cdt/MeshFaceAreas.Bz_next2outercorner)*F(i,j  ).Bz ...
        -(cdt/1.0                     )*F(i,j-1).Bz...
        );
end
for i=MeshParam.Fine_X_from+1:MeshParam.Fine_X_to-1
       % Updated(i,j)=Updated(i,j)+1;
    F(i,j).Ex=...
        ((1.0*cdt)/1.0)*( ...
        (1.0/(1.0*cdt))*F(i,j).Ex ...
        +(cdt/MeshFaceAreas.Bz_outsideboundary)*F(i,j  ).Bz ...
        -(cdt/1.0                    )*F(i,j-1).Bz...
        );
end

j=MeshParam.Fine_Y_to+2;
for i=MeshParam.Fine_X_from-1:...
        (MeshParam.Fine_X_to+1)-(MeshParam.Fine_X_from-1):...
        MeshParam.Fine_X_to+1
       % Updated(i,j)=Updated(i,j)+1;
    F(i,j).Ex=...
        ((1.0*cdt)/1.0)*( ...
        (1.0/(1.0*cdt))*F(i,j).Ex ...
        +(cdt/1.0                )*F(i,j  ).Bz ...
        -(cdt/MeshFaceAreas.Bz_outercorner)*F(i,j-1).Bz...
        );
end
for i=MeshParam.Fine_X_from:...
        MeshParam.Fine_X_to-MeshParam.Fine_X_from:...
        MeshParam.Fine_X_to
       % Updated(i,j)=Updated(i,j)+1;
    F(i,j).Ex=...
        ((1.0*cdt)/1.0)*( ...
        (1.0/(1.0*cdt))*F(i,j).Ex ...
        +(cdt/1.0                     )*F(i,j  ).Bz ...
        -(cdt/MeshFaceAreas.Bz_next2outercorner)*F(i,j-1).Bz...
        );
end
for i=MeshParam.Fine_X_from+1:MeshParam.Fine_X_to-1
    % Updated(i,j)=Updated(i,j)+1;
    F(i,j).Ex=...
        ((1.0*cdt)/1.0)*( ...
        (1.0/(1.0*cdt))*F(i,j).Ex ...
        +(cdt/1.0                    )*F(i,j  ).Bz ...
        -(cdt/MeshFaceAreas.Bz_outsideboundary)*F(i,j-1).Bz...
        );
end

for i=MeshParam.Fine_X_from-1:...
        (MeshParam.Fine_X_to+1)-(MeshParam.Fine_X_from-1):...
        MeshParam.Fine_X_to+1
    
    j=MeshParam.Fine_Y_from;
       % Updated(i,j)=Updated(i,j)+1;
    F(i,j).Ex=...
        (MeshFaceAreas.E_outsideboundary/1.0)*( ...
        (1.0/MeshFaceAreas.E_outsideboundary)*F(i,j).Ex ...
        +(cdt/MeshFaceAreas.Bz_next2outercorner)*F(i,j  ).Bz ...
        -(cdt/MeshFaceAreas.Bz_outercorner     )*F(i,j-1).Bz...
        );
    j=MeshParam.Fine_Y_from+1;
       % Updated(i,j)=Updated(i,j)+1;
    F(i,j).Ex=...
        (MeshFaceAreas.E_outsideboundary/1.0)*( ...
        (1.0/MeshFaceAreas.E_outsideboundary)*F(i,j).Ex ...
        +(cdt/MeshFaceAreas.Bz_outsideboundary )*F(i,j  ).Bz ...
        -(cdt/MeshFaceAreas.Bz_next2outercorner)*F(i,j-1).Bz...
        );
    for j=MeshParam.Fine_Y_from+2:MeshParam.Fine_Y_to-1
           % Updated(i,j)=Updated(i,j)+1;
        F(i,j).Ex=...
            (MeshFaceAreas.E_outsideboundary/1.0)*( ...
            (1.0/MeshFaceAreas.E_outsideboundary)*F(i,j).Ex ...
            +(cdt/MeshFaceAreas.Bz_outsideboundary)*F(i,j  ).Bz ...
            -(cdt/MeshFaceAreas.Bz_outsideboundary)*F(i,j-1).Bz...
            );
    end
    j=MeshParam.Fine_Y_to;
       % Updated(i,j)=Updated(i,j)+1;
    F(i,j).Ex=...
        (MeshFaceAreas.E_outsideboundary/1.0)*( ...
        (1.0/MeshFaceAreas.E_outsideboundary)*F(i,j).Ex ...
        +(cdt/MeshFaceAreas.Bz_next2outercorner)*F(i,j  ).Bz ...
        -(cdt/MeshFaceAreas.Bz_outsideboundary )*F(i,j-1).Bz...
        );
    j=MeshParam.Fine_Y_to+1;
    % Updated(i,j)=Updated(i,j)+1;
    F(i,j).Ex=...
        (MeshFaceAreas.E_outsideboundary/1.0)*( ...
        (1.0/MeshFaceAreas.E_outsideboundary)*F(i,j).Ex ...
        +(cdt/MeshFaceAreas.Bz_outercorner     )*F(i,j  ).Bz ...
        -(cdt/MeshFaceAreas.Bz_next2outercorner)*F(i,j-1).Bz...
        );
end

for j=MeshParam.Fine_Y_from-1:MeshParam.Fine_Y_to+2   
    for i=MeshParam.Fine_X_to+2:MeshParam.Size_X
           % Updated(i,j)=Updated(i,j)+1;
        F(i,j).Ex=((1.0*cdt)/1.0)*( ...
            (1.0/(1.0*cdt))*F(i,j).Ex ...
            + (cdt/1.0)*F(i,j).Bz ...
            - (cdt/1.0)*F(i,j-1).Bz...
            );
    end
end
for j=MeshParam.Fine_Y_to+3:MeshParam.Size_Y
    for i=1:MeshParam.Size_X
           % Updated(i,j)=Updated(i,j)+1;
        F(i,j).Ex=((1.0*cdt)/1.0)*( ...
            (1.0/(1.0*cdt))*F(i,j).Ex ...
            + (cdt/1.0)*F(i,j).Bz ...
            - (cdt/1.0)*F(i,j-1).Bz...
            );
    end
end

%% update Ey
i=1;
for j=1:MeshParam.Size_Y
   % Updated(i,j)=Updated(i,j)+1;
    F(i,j).Ey=((1.0*cdt)/1.0)*( ...
        (1.0/(1.0*cdt))*F(i,j).Ey ...
        -(cdt/1.0)*F(i               ,j).Bz ...
        +(cdt/1.0)*F(MeshParam.Size_X,j).Bz...
        );
end
for j=1:MeshParam.Size_Y
    for i=2:MeshParam.Fine_X_from-2
        % Updated(i,j)=Updated(i,j)+1;
        F(i,j).Ey=((1.0*cdt)/1.0)*( ...
            (1.0/(1.0*cdt))*F(i,j).Ey ...
            -(cdt/1.0)*F(i  ,j).Bz ...
            +(cdt/1.0)*F(i-1,j).Bz...
            );
    end
end
for j=1:MeshParam.Fine_Y_from-2    
    for i=MeshParam.Fine_X_from-1:MeshParam.Fine_X_to+2
           % Updated(i,j)=Updated(i,j)+1;
        F(i,j).Ey=((1.0*cdt)/1.0)*( ...
            (1.0/(1.0*cdt))*F(i,j).Ey ...
            -(cdt/1.0)*F(i  ,j).Bz ...
            +(cdt/1.0)*F(i-1,j).Bz...
            );
    end
end
i=MeshParam.Fine_X_from-1;
for j=MeshParam.Fine_Y_from-1:...
        (MeshParam.Fine_Y_to+1)-(MeshParam.Fine_Y_from-1):...
        MeshParam.Fine_Y_to+1
     % Updated(i,j)=Updated(i,j)+1;
    F(i,j).Ey=...
        ((1.0*cdt)/1.0)*( ...
        (1.0/(1.0*cdt))*F(i,j).Ey ...
        -(cdt/MeshFaceAreas.Bz_outercorner)*F(i  ,j).Bz ...
        +(cdt/1.0                )*F(i-1,j).Bz...
        );
end
for j=MeshParam.Fine_Y_from:...
        MeshParam.Fine_Y_to-MeshParam.Fine_Y_from:...
        MeshParam.Fine_Y_to
       % Updated(i,j)=Updated(i,j)+1;
    F(i,j).Ey=...
        ((1.0*cdt)/1.0)*( ...
        (1.0/(1.0*cdt))*F(i,j).Ey ...
        -(cdt/MeshFaceAreas.Bz_next2outercorner)*F(i  ,j).Bz ...
        +(cdt/1.0                     )*F(i-1,j).Bz...
        );
end
for j=MeshParam.Fine_Y_from+1:MeshParam.Fine_Y_to-1
       % Updated(i,j)=Updated(i,j)+1;
    F(i,j).Ey=...
        ((1.0*cdt)/1.0)*( ...
        (1.0/(1.0*cdt))*F(i,j).Ey ...
        -(cdt/MeshFaceAreas.Bz_outsideboundary)*F(i  ,j).Bz ...
        +(cdt/1.0                    )*F(i-1,j).Bz...
        );
end
i=MeshParam.Fine_X_to+2;
for j=MeshParam.Fine_Y_from-1:...
        (MeshParam.Fine_Y_to+1)-(MeshParam.Fine_Y_from-1):...
        MeshParam.Fine_Y_to+1
       % Updated(i,j)=Updated(i,j)+1;
    F(i,j).Ey=...
        ((1.0*cdt)/1.0)*( ...
        (1.0/(1.0*cdt))*F(i,j).Ey ...
        -(cdt/1.0                )*F(i  ,j).Bz ...
        +(cdt/MeshFaceAreas.Bz_outercorner)*F(i-1,j).Bz...
        );
end
for j=MeshParam.Fine_Y_from:...
        MeshParam.Fine_Y_to-MeshParam.Fine_Y_from:...
        MeshParam.Fine_Y_to
       % Updated(i,j)=Updated(i,j)+1;
    F(i,j).Ey=...
        ((1.0*cdt)/1.0)*( ...
        (1.0/(1.0*cdt))*F(i,j).Ey ...
        -(cdt/1.0                     )*F(i  ,j).Bz ...
        +(cdt/MeshFaceAreas.Bz_next2outercorner)*F(i-1,j).Bz...
        );
end
for j=MeshParam.Fine_Y_from+1:MeshParam.Fine_Y_to-1
       % Updated(i,j)=Updated(i,j)+1;
    F(i,j).Ey=...
        ((1.0*cdt)/1.0)*( ...
        (1.0/(1.0*cdt))*F(i,j).Ey ...
        -(cdt/1.0                    )*F(i  ,j).Bz ...
        +(cdt/MeshFaceAreas.Bz_outsideboundary)*F(i-1,j).Bz...
        );
end

for j=MeshParam.Fine_Y_from-1:...
        (MeshParam.Fine_Y_to+1)-(MeshParam.Fine_Y_from-1):...
        MeshParam.Fine_Y_to+1
    
    i=MeshParam.Fine_X_from;
       % Updated(i,j)=Updated(i,j)+1;
    F(i,j).Ey=...
        (MeshFaceAreas.E_outsideboundary/1.0)*( ...
        (1.0/MeshFaceAreas.E_outsideboundary)*F(i,j).Ey ...
        -(cdt/MeshFaceAreas.Bz_next2outercorner)*F(i  ,j).Bz ...
        +(cdt/MeshFaceAreas.Bz_outercorner     )*F(i-1,j).Bz...
        );
    i=MeshParam.Fine_X_from+1;
       % Updated(i,j)=Updated(i,j)+1;
    F(i,j).Ey=...
        (MeshFaceAreas.E_outsideboundary/1.0)*( ...
        (1.0/MeshFaceAreas.E_outsideboundary)*F(i,j).Ey ...
        -(cdt/MeshFaceAreas.Bz_outsideboundary )*F(i  ,j).Bz ...
        +(cdt/MeshFaceAreas.Bz_next2outercorner)*F(i-1,j).Bz...
        );
    for i=MeshParam.Fine_X_from+2:MeshParam.Fine_X_to-1
           % Updated(i,j)=Updated(i,j)+1;
        F(i,j).Ey=...
            (MeshFaceAreas.E_outsideboundary/1.0)*( ...
            (1.0/MeshFaceAreas.E_outsideboundary)*F(i,j).Ey ...
            -(cdt/MeshFaceAreas.Bz_outsideboundary)*F(i  ,j).Bz ...
            +(cdt/MeshFaceAreas.Bz_outsideboundary)*F(i-1,j).Bz...
            );
    end
    i=MeshParam.Fine_X_to;
    % Updated(i,j)=Updated(i,j)+1;
    F(i,j).Ey=...
        (MeshFaceAreas.E_outsideboundary/1.0)*( ...
        (1.0/MeshFaceAreas.E_outsideboundary)*F(i,j).Ey ...
        -(cdt/MeshFaceAreas.Bz_next2outercorner)*F(i  ,j).Bz ...
        +(cdt/MeshFaceAreas.Bz_outsideboundary )*F(i-1,j).Bz...
        );
    i=MeshParam.Fine_X_to+1;
    % Updated(i,j)=Updated(i,j)+1;
    F(i,j).Ey=...
        (MeshFaceAreas.E_outsideboundary/1.0)*( ...
        (1.0/MeshFaceAreas.E_outsideboundary)*F(i,j).Ey ...
        -(cdt/MeshFaceAreas.Bz_outercorner     )*F(i  ,j).Bz ...
        +(cdt/MeshFaceAreas.Bz_next2outercorner)*F(i-1,j).Bz...
        );
end

for j=MeshParam.Fine_Y_to+2:MeshParam.Size_Y  
    for i=MeshParam.Fine_X_from-1:MeshParam.Fine_X_to+2
           % Updated(i,j)=Updated(i,j)+1;
        F(i,j).Ey=((1.0*cdt)/1.0)*( ...
            (1.0/(1.0*cdt))*F(i,j).Ey ...
            - (cdt/1.0)*F(i  ,j).Bz ...
            + (cdt/1.0)*F(i-1,j).Bz...
            );
    end
end
for j=1:MeshParam.Size_Y
    for i=MeshParam.Fine_X_to+3:MeshParam.Size_X
        % Updated(i,j)=Updated(i,j)+1;
        F(i,j).Ey=((1.0*cdt)/1.0)*( ...
            (1.0/(1.0*cdt))*F(i,j).Ey ...
            - (cdt/1.0)*F(i  ,j).Bz ...
            + (cdt/1.0)*F(i-1,j).Bz...
            );
    end
end
%% end 
end

%% 
function [F,Updated]=Update_E_RegionBoundary_FirstTimeSec(F,cdt,cdt_subgrid,MeshParam,MeshFaceAreas,Updated)

%% update Ex
j=MeshParam.Fine_Y_from;

i=MeshParam.Fine_X_from;
F(i,j).ExPreserve=0;
localjIdx=1;
localiIdx=1;
% Updated(i,j)=Updated(i,j)+1;
F(i,j).Ex(localiIdx,localjIdx)=(MeshFaceAreas.E_innercorner/(sqrt(10)/4.0))*( ...
    ((sqrt(10)/4.0)/MeshFaceAreas.E_innercorner)*F(i,j).Ex(localiIdx,localjIdx) ...
    + (cdt_subgrid/MeshFaceAreas.Bz_innercorner     )*F(i,j  ).Bz(localiIdx,localjIdx) ...
    - (cdt        /MeshFaceAreas.Bz_next2outercorner)*F(i,j-1).Bz...
    );
F(i,j).ExPreserve=F(i,j).ExPreserve+F(i,j).Ex(localiIdx,localjIdx);
localiIdx=2;
% Updated(i,j)=Updated(i,j)+1;
F(i,j).Ex(localiIdx,localjIdx)=((0.5*cdt_subgrid)/0.75)*( ...
    (0.75/(0.5*cdt_subgrid))*F(i,j).Ex(localiIdx,localjIdx) ...
    + (cdt_subgrid/MeshFaceAreas.Bz_insideboundary  )*F(i,j  ).Bz(localiIdx,localjIdx) ...
    - (cdt        /MeshFaceAreas.Bz_next2outercorner)*F(i,j-1).Bz...
    );
F(i,j).ExPreserve=F(i,j).ExPreserve+F(i,j).Ex(localiIdx,localjIdx);
localjIdx=2;
localiIdx=1;
% Updated(i,j)=Updated(i,j)+1;
F(i,j).Ex(localiIdx,localjIdx)=(MeshFaceAreas.E_insideboundary_smaller/0.5)*( ...
    (0.5/MeshFaceAreas.E_insideboundary_smaller)*F(i,j).Ex(localiIdx,localjIdx) ...
    + (cdt_subgrid/MeshFaceAreas.Bz_insideboundary )*F(i,j  ).Bz(localiIdx,localjIdx  ) ...
    - (cdt_subgrid/MeshFaceAreas.Bz_innercorner    )*F(i,j  ).Bz(localiIdx,localjIdx-1)...
    );
localiIdx=2;
% Updated(i,j)=Updated(i,j)+1;
F(i,j).Ex(localiIdx,localjIdx)=((0.5*cdt_subgrid)/0.5)*( ...
    (0.5/(0.5*cdt_subgrid))*F(i,j).Ex(localiIdx,localjIdx) ...
    + (cdt_subgrid/0.25                  )*F(i,j  ).Bz(localiIdx,localjIdx  ) ...
    - (cdt_subgrid/MeshFaceAreas.Bz_insideboundary)*F(i,j  ).Bz(localiIdx,localjIdx-1)...
    );

i=MeshParam.Fine_X_to;
F(i,j).ExPreserve=0;
localjIdx=1;
localiIdx=1;
% Updated(i,j)=Updated(i,j)+1;
F(i,j).Ex(localiIdx,localjIdx)=((0.5*cdt_subgrid)/0.75)*( ...
    (0.75/(0.5*cdt_subgrid))*F(i,j).Ex(localiIdx,localjIdx) ...
    + (cdt_subgrid/MeshFaceAreas.Bz_insideboundary  )*F(i,j  ).Bz(localiIdx,localjIdx) ...
    - (cdt        /MeshFaceAreas.Bz_next2outercorner)*F(i,j-1).Bz...
    );
F(i,j).ExPreserve=F(i,j).ExPreserve+F(i,j).Ex(localiIdx,localjIdx);
localiIdx=2;
% Updated(i,j)=Updated(i,j)+1;
F(i,j).Ex(localiIdx,localjIdx)=(MeshFaceAreas.E_innercorner/(sqrt(10)/4.0))*( ...
    ((sqrt(10)/4.0)/MeshFaceAreas.E_innercorner)*F(i,j).Ex(localiIdx,localjIdx) ...
    + (cdt_subgrid/MeshFaceAreas.Bz_innercorner     )*F(i,j  ).Bz(localiIdx,localjIdx) ...
    - (cdt        /MeshFaceAreas.Bz_next2outercorner)*F(i,j-1).Bz...
    );
F(i,j).ExPreserve=F(i,j).ExPreserve+F(i,j).Ex(localiIdx,localjIdx);
localjIdx=2;
localiIdx=1;
% Updated(i,j)=Updated(i,j)+1;
F(i,j).Ex(localiIdx,localjIdx)=((0.5*cdt_subgrid)/0.5)*( ...
    (0.5/(0.5*cdt_subgrid))*F(i,j).Ex(localiIdx,localjIdx) ...
    + (cdt_subgrid/0.25                  )*F(i,j  ).Bz(localiIdx,localjIdx  ) ...
    - (cdt_subgrid/MeshFaceAreas.Bz_insideboundary)*F(i,j  ).Bz(localiIdx,localjIdx-1)...
    );
localiIdx=2;
% Updated(i,j)=Updated(i,j)+1;
F(i,j).Ex(localiIdx,localjIdx)=(MeshFaceAreas.E_insideboundary_smaller/0.5)*( ...
    (0.5/MeshFaceAreas.E_insideboundary_smaller)*F(i,j).Ex(localiIdx,localjIdx) ...
    + (cdt_subgrid/MeshFaceAreas.Bz_insideboundary )*F(i,j  ).Bz(localiIdx,localjIdx  ) ...
    - (cdt_subgrid/MeshFaceAreas.Bz_innercorner    )*F(i,j  ).Bz(localiIdx,localjIdx-1)...
    );

for i=MeshParam.Fine_X_from+1:MeshParam.Fine_X_to-1
    F(i,j).ExPreserve=0;
    for localiIdx=1:2
        localjIdx=1;
        % Updated(i,j)=Updated(i,j)+1;
        F(i,j).Ex(localiIdx,localjIdx)=((0.5*cdt_subgrid)/0.75)*( ...
            (0.75/(0.5*cdt_subgrid))*F(i,j).Ex(localiIdx,localjIdx) ...
            + (cdt_subgrid/MeshFaceAreas.Bz_insideboundary )*F(i,j  ).Bz(localiIdx,localjIdx) ...
            - (cdt        /MeshFaceAreas.Bz_outsideboundary)*F(i,j-1).Bz...
            );
        F(i,j).ExPreserve=F(i,j).ExPreserve+F(i,j).Ex(localiIdx,localjIdx);
        localjIdx=2;
       % Updated(i,j)=Updated(i,j)+1;
        F(i,j).Ex(localiIdx,localjIdx)=((0.5*cdt_subgrid)/0.5)*( ...
            (0.5/(0.5*cdt_subgrid))*F(i,j).Ex(localiIdx,localjIdx) ...
            + (cdt_subgrid/0.25                  )*F(i,j  ).Bz(localiIdx,localjIdx  ) ...
            - (cdt_subgrid/MeshFaceAreas.Bz_insideboundary)*F(i,j  ).Bz(localiIdx,localjIdx-1)...
            );
    end
end

j=MeshParam.Fine_Y_to;
i=MeshParam.Fine_X_from;
localjIdx=1;
localiIdx=1;
% Updated(i,j)=Updated(i,j)+1;
F(i,j).Ex(localiIdx,localjIdx)=(MeshFaceAreas.E_insideboundary_larger/0.5)*( ...
    (0.5/MeshFaceAreas.E_insideboundary_larger)*F(i,j).Ex(localiIdx,localjIdx) ...
    + (cdt_subgrid/MeshFaceAreas.Bz_insideboundary)*F(i,j  ).Bz(localiIdx,localjIdx  )...
    - (cdt_subgrid/MeshFaceAreas.Bz_insideboundary)*F(i,j-1).Bz(localiIdx,localjIdx+1) ...
    );
localiIdx=2;
% Updated(i,j)=Updated(i,j)+1;
F(i,j).Ex(localiIdx,localjIdx)=((0.5*cdt_subgrid)/0.5)*( ...
    (0.5/(0.5*cdt_subgrid))*F(i,j).Ex(localiIdx,localjIdx) ...
    + (cdt_subgrid/0.25)*F(i,j  ).Bz(localiIdx,localjIdx  )...
    - (cdt_subgrid/0.25)*F(i,j-1).Bz(localiIdx,localjIdx+1) ...
    );
localjIdx=2;
localiIdx=1;
% Updated(i,j)=Updated(i,j)+1;
F(i,j).Ex(localiIdx,localjIdx)=(MeshFaceAreas.E_insideboundary_smaller/0.5)*( ...
    (0.5/MeshFaceAreas.E_insideboundary_smaller)*F(i,j).Ex(localiIdx,localjIdx) ...
    + (cdt_subgrid/MeshFaceAreas.Bz_innercorner   )*F(i,j  ).Bz(localiIdx,localjIdx  )...
    - (cdt_subgrid/MeshFaceAreas.Bz_insideboundary)*F(i,j  ).Bz(localiIdx,localjIdx-1) ...
    );
localiIdx=2;
% Updated(i,j)=Updated(i,j)+1;
F(i,j).Ex(localiIdx,localjIdx)=((0.5*cdt_subgrid)/0.5)*( ...
    (0.5/(0.5*cdt_subgrid))*F(i,j).Ex(localiIdx,localjIdx) ...
    + (cdt_subgrid/MeshFaceAreas.Bz_insideboundary)*F(i,j  ).Bz(localiIdx,localjIdx  )...
    - (cdt_subgrid/0.25                  )*F(i,j  ).Bz(localiIdx,localjIdx-1) ...
    );
for i=MeshParam.Fine_X_from+1:MeshParam.Fine_X_to-1
    localjIdx=1;
    for localiIdx=1:2
       % Updated(i,j)=Updated(i,j)+1;
        F(i,j).Ex(localiIdx,localjIdx)=((0.5*cdt_subgrid)/0.5)*( ...
            (0.5/(0.5*cdt_subgrid))*F(i,j).Ex(localiIdx,localjIdx) ...
            + (cdt_subgrid/0.25)*F(i,j  ).Bz(localiIdx,localjIdx  )...
            - (cdt_subgrid/0.25)*F(i,j-1).Bz(localiIdx,localjIdx+1) ...
            );
    end
    localjIdx=2;
    for localiIdx=1:2
       % Updated(i,j)=Updated(i,j)+1;
        F(i,j).Ex(localiIdx,localjIdx)=((0.5*cdt_subgrid)/0.5)*( ...
            (0.5/(0.5*cdt_subgrid))*F(i,j).Ex(localiIdx,localjIdx) ...
            + (cdt_subgrid/MeshFaceAreas.Bz_insideboundary)*F(i,j  ).Bz(localiIdx,localjIdx  )...
            - (cdt_subgrid/0.25                  )*F(i,j  ).Bz(localiIdx,localjIdx-1) ...
            );
    end
end
i=MeshParam.Fine_X_to;
localjIdx=1;
localiIdx=1;
% Updated(i,j)=Updated(i,j)+1;
F(i,j).Ex(localiIdx,localjIdx)=((0.5*cdt_subgrid)/0.5)*( ...
    (0.5/(0.5*cdt_subgrid))*F(i,j).Ex(localiIdx,localjIdx) ...
    + (cdt_subgrid/0.25)*F(i,j  ).Bz(localiIdx,localjIdx  )...
    - (cdt_subgrid/0.25)*F(i,j-1).Bz(localiIdx,localjIdx+1) ...
    );
localiIdx=2;
% Updated(i,j)=Updated(i,j)+1;
F(i,j).Ex(localiIdx,localjIdx)=(MeshFaceAreas.E_insideboundary_larger/0.5)*( ...
    (0.5/MeshFaceAreas.E_insideboundary_larger)*F(i,j).Ex(localiIdx,localjIdx) ...
    + (cdt_subgrid/MeshFaceAreas.Bz_insideboundary)*F(i,j  ).Bz(localiIdx,localjIdx  )...
    - (cdt_subgrid/MeshFaceAreas.Bz_insideboundary)*F(i,j-1).Bz(localiIdx,localjIdx+1) ...
    );

localjIdx=2;
localiIdx=1;
% Updated(i,j)=Updated(i,j)+1;
F(i,j).Ex(localiIdx,localjIdx)=((0.5*cdt_subgrid)/0.5)*( ...
    (0.5/(0.5*cdt_subgrid))*F(i,j).Ex(localiIdx,localjIdx) ...
    + (cdt_subgrid/MeshFaceAreas.Bz_insideboundary)*F(i,j  ).Bz(localiIdx,localjIdx  )...
    - (cdt_subgrid/0.25                  )*F(i,j  ).Bz(localiIdx,localjIdx-1) ...
    );
localiIdx=2;
% Updated(i,j)=Updated(i,j)+1;
F(i,j).Ex(localiIdx,localjIdx)=(MeshFaceAreas.E_insideboundary_smaller/0.5)*( ...
    (0.5/MeshFaceAreas.E_insideboundary_smaller)*F(i,j).Ex(localiIdx,localjIdx) ...
    + (cdt_subgrid/MeshFaceAreas.Bz_innercorner   )*F(i,j  ).Bz(localiIdx,localjIdx  )...
    - (cdt_subgrid/MeshFaceAreas.Bz_insideboundary)*F(i,j  ).Bz(localiIdx,localjIdx-1) ...
    );

j=MeshParam.Fine_Y_to+1;

i=MeshParam.Fine_X_from;
F(i,j).ExPreserve=0;
localjIdx=1;
localiIdx=1;
% Updated(i,j)=Updated(i,j)+1;
F(i,j).Ex(localiIdx,localjIdx)=(MeshFaceAreas.E_innercorner/(sqrt(10)/4.0))*( ...
    ((sqrt(10)/4.0)/MeshFaceAreas.E_innercorner)*F(i,j).Ex(localiIdx,localjIdx) ...
    + (cdt        /MeshFaceAreas.Bz_next2outercorner)*F(i,j  ).Bz ...
    - (cdt_subgrid/MeshFaceAreas.Bz_innercorner     )*F(i,j-1).Bz(localiIdx,localjIdx+1)...
    );
F(i,j).ExPreserve=F(i,j).ExPreserve+F(i,j).Ex(localiIdx,localjIdx);
localiIdx=2;
% Updated(i,j)=Updated(i,j)+1;
F(i,j).Ex(localiIdx,localjIdx)=((0.5*cdt_subgrid)/0.75)*( ...
    (0.75/(0.5*cdt_subgrid))*F(i,j).Ex(localiIdx,localjIdx) ...
    + (cdt        /MeshFaceAreas.Bz_next2outercorner)*F(i,j  ).Bz ...
    - (cdt_subgrid/MeshFaceAreas.Bz_insideboundary  )*F(i,j-1).Bz(localiIdx,localjIdx+1) ...
    );
F(i,j).ExPreserve=F(i,j).ExPreserve+F(i,j).Ex(localiIdx,localjIdx);

i=MeshParam.Fine_X_to;
F(i,j).ExPreserve=0;
localjIdx=1;
localiIdx=1;
% Updated(i,j)=Updated(i,j)+1;
F(i,j).Ex(localiIdx,localjIdx)=((0.5*cdt_subgrid)/0.75)*( ...
    (0.75/(0.5*cdt_subgrid))*F(i,j).Ex(localiIdx,localjIdx) ...
    + (cdt        /MeshFaceAreas.Bz_next2outercorner)*F(i,j  ).Bz ...
    - (cdt_subgrid/MeshFaceAreas.Bz_insideboundary  )*F(i,j-1).Bz(localiIdx,localjIdx+1) ...
    );
F(i,j).ExPreserve=F(i,j).ExPreserve+F(i,j).Ex(localiIdx,localjIdx);
localiIdx=2;
% Updated(i,j)=Updated(i,j)+1;
F(i,j).Ex(localiIdx,localjIdx)=(MeshFaceAreas.E_innercorner/(sqrt(10)/4.0))*( ...
    ((sqrt(10)/4.0)/MeshFaceAreas.E_innercorner)*F(i,j).Ex(localiIdx,localjIdx) ...
    + (cdt        /MeshFaceAreas.Bz_next2outercorner)*F(i,j  ).Bz ...
    - (cdt_subgrid/MeshFaceAreas.Bz_innercorner     )*F(i,j-1).Bz(localiIdx,localjIdx+1)...
    );
F(i,j).ExPreserve=F(i,j).ExPreserve+F(i,j).Ex(localiIdx,localjIdx);

for i=MeshParam.Fine_X_from+1:MeshParam.Fine_X_to-1
    F(i,j).ExPreserve=0;
    localjIdx=1;
    for localiIdx=1:2
       % Updated(i,j)=Updated(i,j)+1;
        F(i,j).Ex(localiIdx,localjIdx)=((0.5*cdt_subgrid)/0.75)*( ...
            (0.75/(0.5*cdt_subgrid))*F(i,j).Ex(localiIdx,localjIdx) ...
            + (cdt        /MeshFaceAreas.Bz_outsideboundary)*F(i,j  ).Bz...
            - (cdt_subgrid/MeshFaceAreas.Bz_insideboundary )*F(i,j-1).Bz(localiIdx,localjIdx+1) ...
            );
        F(i,j).ExPreserve=F(i,j).ExPreserve+F(i,j).Ex(localiIdx,localjIdx);
    end
end

i=MeshParam.Fine_X_from;
for j=MeshParam.Fine_Y_from+1:MeshParam.Fine_Y_to-1
    localjIdx=1;
    localiIdx=1;
   % Updated(i,j)=Updated(i,j)+1;
    F(i,j).Ex(localiIdx,localjIdx)=(MeshFaceAreas.E_insideboundary_larger/0.5)*( ...
        (0.5/MeshFaceAreas.E_insideboundary_larger)*F(i,j).Ex(localiIdx,localjIdx) ...
        + (cdt_subgrid/MeshFaceAreas.Bz_insideboundary)*F(i,j  ).Bz(localiIdx,localjIdx  )...
        - (cdt_subgrid/MeshFaceAreas.Bz_insideboundary)*F(i,j-1).Bz(localiIdx,localjIdx+1) ...
        );
    localiIdx=2;
   % Updated(i,j)=Updated(i,j)+1;
    F(i,j).Ex(localiIdx,localjIdx)=((0.5*cdt_subgrid)/0.5)*( ...
        (0.5/(0.5*cdt_subgrid))*F(i,j).Ex(localiIdx,localjIdx) ...
        + (cdt_subgrid/0.25)*F(i,j  ).Bz(localiIdx,localjIdx  )...
        - (cdt_subgrid/0.25)*F(i,j-1).Bz(localiIdx,localjIdx+1) ...
        );
    
    localjIdx=2;
    localiIdx=1;
   % Updated(i,j)=Updated(i,j)+1;
    F(i,j).Ex(localiIdx,localjIdx)=(MeshFaceAreas.E_insideboundary_smaller/0.5)*( ...
        (0.5/MeshFaceAreas.E_insideboundary_smaller)*F(i,j).Ex(localiIdx,localjIdx) ...
        + (cdt_subgrid/MeshFaceAreas.Bz_insideboundary)*F(i,j  ).Bz(localiIdx,localjIdx  )...
        - (cdt_subgrid/MeshFaceAreas.Bz_insideboundary)*F(i,j  ).Bz(localiIdx,localjIdx-1) ...
        );
    localiIdx=2;
   % Updated(i,j)=Updated(i,j)+1;
    F(i,j).Ex(localiIdx,localjIdx)=((0.5*cdt_subgrid)/0.5)*( ...
        (0.5/(0.5*cdt_subgrid))*F(i,j).Ex(localiIdx,localjIdx) ...
        + (cdt_subgrid/0.25)*F(i,j  ).Bz(localiIdx,localjIdx  )...
        - (cdt_subgrid/0.25)*F(i,j  ).Bz(localiIdx,localjIdx-1) ...
        );
end
i=MeshParam.Fine_X_to;
for j=MeshParam.Fine_Y_from+1:MeshParam.Fine_Y_to-1
    localjIdx=1;
    localiIdx=1;
   % Updated(i,j)=Updated(i,j)+1;
    F(i,j).Ex(localiIdx,localjIdx)=((0.5*cdt_subgrid)/0.5)*( ...
        (0.5/(0.5*cdt_subgrid))*F(i,j).Ex(localiIdx,localjIdx) ...
        + (cdt_subgrid/0.25)*F(i,j  ).Bz(localiIdx,localjIdx  )...
        - (cdt_subgrid/0.25)*F(i,j-1).Bz(localiIdx,localjIdx+1) ...
        );
    localiIdx=2;
   % Updated(i,j)=Updated(i,j)+1;
    F(i,j).Ex(localiIdx,localjIdx)=(MeshFaceAreas.E_insideboundary_larger/0.5)*( ...
        (0.5/MeshFaceAreas.E_insideboundary_larger)*F(i,j).Ex(localiIdx,localjIdx) ...
        + (cdt_subgrid/MeshFaceAreas.Bz_insideboundary)*F(i,j  ).Bz(localiIdx,localjIdx  )...
        - (cdt_subgrid/MeshFaceAreas.Bz_insideboundary)*F(i,j-1).Bz(localiIdx,localjIdx+1) ...
        );  
    
    localjIdx=2;
    localiIdx=1;
   % Updated(i,j)=Updated(i,j)+1;
    F(i,j).Ex(localiIdx,localjIdx)=((0.5*cdt_subgrid)/0.5)*( ...
        (0.5/(0.5*cdt_subgrid))*F(i,j).Ex(localiIdx,localjIdx) ...
        + (cdt_subgrid/0.25)*F(i,j  ).Bz(localiIdx,localjIdx  )...
        - (cdt_subgrid/0.25)*F(i,j  ).Bz(localiIdx,localjIdx-1) ...
        );
    localiIdx=2;
  %  Updated(i,j)=Updated(i,j)+1;
    F(i,j).Ex(localiIdx,localjIdx)=(MeshFaceAreas.E_insideboundary_smaller/0.5)*( ...
        (0.5/MeshFaceAreas.E_insideboundary_smaller)*F(i,j).Ex(localiIdx,localjIdx) ...
        + (cdt_subgrid/MeshFaceAreas.Bz_insideboundary)*F(i,j  ).Bz(localiIdx,localjIdx  )...
        - (cdt_subgrid/MeshFaceAreas.Bz_insideboundary)*F(i,j  ).Bz(localiIdx,localjIdx-1) ...
        );
end

%% update Ey
i=MeshParam.Fine_X_from;

j=MeshParam.Fine_Y_from;
F(i,j).EyPreserve=0;
localiIdx=1;
localjIdx=1;
% Updated(i,j)=Updated(i,j)+1;
F(i,j).Ey(localiIdx,localjIdx)=(MeshFaceAreas.E_innercorner/(sqrt(10)/4.0))*( ...
    ((sqrt(10)/4.0)/MeshFaceAreas.E_innercorner)*F(i,j).Ey(localiIdx,localjIdx) ...
    - (cdt_subgrid/MeshFaceAreas.Bz_innercorner     )*F(i  ,j).Bz(localiIdx,localjIdx) ...
    + (cdt        /MeshFaceAreas.Bz_next2outercorner)*F(i-1,j).Bz...
    );
F(i,j).EyPreserve=F(i,j).EyPreserve+F(i,j).Ey(localiIdx,localjIdx);
localjIdx=2;
% Updated(i,j)=Updated(i,j)+1;
F(i,j).Ey(localiIdx,localjIdx)=((0.5*cdt_subgrid)/0.75)*( ...
    (0.75/(0.5*cdt_subgrid))*F(i,j).Ey(localiIdx,localjIdx) ...
    - (cdt_subgrid/MeshFaceAreas.Bz_insideboundary  )*F(i  ,j).Bz(localiIdx,localjIdx) ...
    + (cdt        /MeshFaceAreas.Bz_next2outercorner)*F(i-1,j).Bz...
    );
F(i,j).EyPreserve=F(i,j).EyPreserve+F(i,j).Ey(localiIdx,localjIdx);
localiIdx=2;
localjIdx=1;
% Updated(i,j)=Updated(i,j)+1;
F(i,j).Ey(localiIdx,localjIdx)=(MeshFaceAreas.E_insideboundary_smaller/0.5)*( ...
    (0.5/MeshFaceAreas.E_insideboundary_smaller)*F(i,j).Ey(localiIdx,localjIdx) ...
    - (cdt_subgrid/MeshFaceAreas.Bz_insideboundary )*F(i  ,j).Bz(localiIdx  ,localjIdx) ...
    + (cdt_subgrid/MeshFaceAreas.Bz_innercorner    )*F(i  ,j).Bz(localiIdx-1,localjIdx)...
    );
localjIdx=2;
% Updated(i,j)=Updated(i,j)+1;
F(i,j).Ey(localiIdx,localjIdx)=((0.5*cdt_subgrid)/0.5)*( ...
    (0.5/(0.5*cdt_subgrid))*F(i,j).Ey(localiIdx,localjIdx) ...
    - (cdt_subgrid/0.25                  )*F(i  ,j).Bz(localiIdx  ,localjIdx) ...
    + (cdt_subgrid/MeshFaceAreas.Bz_insideboundary)*F(i  ,j).Bz(localiIdx-1,localjIdx)...
    );

j=MeshParam.Fine_Y_to;
F(i,j).EyPreserve=0;
localiIdx=1;
localjIdx=1;
% Updated(i,j)=Updated(i,j)+1;
F(i,j).Ey(localiIdx,localjIdx)=((0.5*cdt_subgrid)/0.75)*( ...
    (0.75/(0.5*cdt_subgrid))*F(i,j).Ey(localiIdx,localjIdx) ...
    - (cdt_subgrid/MeshFaceAreas.Bz_insideboundary  )*F(i  ,j).Bz(localiIdx,localjIdx) ...
    + (cdt        /MeshFaceAreas.Bz_next2outercorner)*F(i-1,j).Bz...
    );
F(i,j).EyPreserve=F(i,j).EyPreserve+F(i,j).Ey(localiIdx,localjIdx);
localjIdx=2;
% Updated(i,j)=Updated(i,j)+1;
F(i,j).Ey(localiIdx,localjIdx)=(MeshFaceAreas.E_innercorner/(sqrt(10)/4.0))*( ...
    ((sqrt(10)/4.0)/MeshFaceAreas.E_innercorner)*F(i,j).Ey(localiIdx,localjIdx) ...
    - (cdt_subgrid/MeshFaceAreas.Bz_innercorner     )*F(i  ,j).Bz(localiIdx,localjIdx) ...
    + (cdt        /MeshFaceAreas.Bz_next2outercorner)*F(i-1,j).Bz...
    );
F(i,j).EyPreserve=F(i,j).EyPreserve+F(i,j).Ey(localiIdx,localjIdx);
localiIdx=2;
localjIdx=1;
% Updated(i,j)=Updated(i,j)+1;
F(i,j).Ey(localiIdx,localjIdx)=((0.5*cdt_subgrid)/0.5)*( ...
    (0.5/(0.5*cdt_subgrid))*F(i,j).Ey(localiIdx,localjIdx) ...
    - (cdt_subgrid/0.25                  )*F(i  ,j).Bz(localiIdx  ,localjIdx) ...
    + (cdt_subgrid/MeshFaceAreas.Bz_insideboundary)*F(i  ,j).Bz(localiIdx-1,localjIdx)...
    );
localjIdx=2;
% Updated(i,j)=Updated(i,j)+1;
F(i,j).Ey(localiIdx,localjIdx)=(MeshFaceAreas.E_insideboundary_smaller/0.5)*( ...
    (0.5/MeshFaceAreas.E_insideboundary_smaller)*F(i,j).Ey(localiIdx,localjIdx) ...
    - (cdt_subgrid/MeshFaceAreas.Bz_insideboundary )*F(i  ,j).Bz(localiIdx  ,localjIdx) ...
    + (cdt_subgrid/MeshFaceAreas.Bz_innercorner    )*F(i  ,j).Bz(localiIdx-1,localjIdx)...
    );

for j=MeshParam.Fine_Y_from+1:MeshParam.Fine_Y_to-1
    F(i,j).EyPreserve=0;
    for localjIdx=1:2
        localiIdx=1;
        % Updated(i,j)=Updated(i,j)+1;
        F(i,j).Ey(localiIdx,localjIdx)=((0.5*cdt_subgrid)/0.75)*( ...
            (0.75/(0.5*cdt_subgrid))*F(i,j).Ey(localiIdx,localjIdx) ...
            - (cdt_subgrid/MeshFaceAreas.Bz_insideboundary )*F(i  ,j).Bz(localiIdx,localjIdx) ...
            + (cdt        /MeshFaceAreas.Bz_outsideboundary)*F(i-1,j).Bz...
            );
        F(i,j).EyPreserve=F(i,j).EyPreserve+F(i,j).Ey(localiIdx,localjIdx);
        localiIdx=2;
       % Updated(i,j)=Updated(i,j)+1;
        F(i,j).Ey(localiIdx,localjIdx)=((0.5*cdt_subgrid)/0.5)*( ...
            (0.5/(0.5*cdt_subgrid))*F(i,j).Ey(localiIdx,localjIdx) ...
            - (cdt_subgrid/0.25                  )*F(i  ,j).Bz(localiIdx  ,localjIdx) ...
            + (cdt_subgrid/MeshFaceAreas.Bz_insideboundary)*F(i  ,j).Bz(localiIdx-1,localjIdx)...
            );
    end
end

i=MeshParam.Fine_X_to;
j=MeshParam.Fine_Y_from;
localiIdx=1;
localjIdx=1;
% Updated(i,j)=Updated(i,j)+1;
F(i,j).Ey(localiIdx,localjIdx)=(MeshFaceAreas.E_insideboundary_larger/0.5)*( ...
    (0.5/MeshFaceAreas.E_insideboundary_larger)*F(i,j).Ey(localiIdx,localjIdx) ...
    - (cdt_subgrid/MeshFaceAreas.Bz_insideboundary)*F(i  ,j).Bz(localiIdx  ,localjIdx)...
    + (cdt_subgrid/MeshFaceAreas.Bz_insideboundary)*F(i-1,j).Bz(localiIdx+1,localjIdx) ...
    );
localjIdx=2;
% Updated(i,j)=Updated(i,j)+1;
F(i,j).Ey(localiIdx,localjIdx)=((0.5*cdt_subgrid)/0.5)*( ...
    (0.5/(0.5*cdt_subgrid))*F(i,j).Ey(localiIdx,localjIdx) ...
    - (cdt_subgrid/0.25)*F(i  ,j).Bz(localiIdx  ,localjIdx)...
    + (cdt_subgrid/0.25)*F(i-1,j).Bz(localiIdx+1,localjIdx) ...
    );
localiIdx=2;
localjIdx=1;
% Updated(i,j)=Updated(i,j)+1;
F(i,j).Ey(localiIdx,localjIdx)=(MeshFaceAreas.E_insideboundary_smaller/0.5)*( ...
    (0.5/MeshFaceAreas.E_insideboundary_smaller)*F(i,j).Ey(localiIdx,localjIdx) ...
    - (cdt_subgrid/MeshFaceAreas.Bz_innercorner   )*F(i  ,j).Bz(localiIdx  ,localjIdx)...
    + (cdt_subgrid/MeshFaceAreas.Bz_insideboundary)*F(i  ,j).Bz(localiIdx-1,localjIdx) ...
    );
localjIdx=2;
% Updated(i,j)=Updated(i,j)+1;
F(i,j).Ey(localiIdx,localjIdx)=((0.5*cdt_subgrid)/0.5)*( ...
    (0.5/(0.5*cdt_subgrid))*F(i,j).Ey(localiIdx,localjIdx) ...
    - (cdt_subgrid/MeshFaceAreas.Bz_insideboundary)*F(i  ,j).Bz(localiIdx  ,localjIdx)...
    + (cdt_subgrid/0.25                  )*F(i  ,j).Bz(localiIdx-1,localjIdx) ...
    );
for j=MeshParam.Fine_Y_from+1:MeshParam.Fine_Y_to-1
    localiIdx=1;
    for localjIdx=1:2
       % Updated(i,j)=Updated(i,j)+1;
        F(i,j).Ey(localiIdx,localjIdx)=((0.5*cdt_subgrid)/0.5)*( ...
            (0.5/(0.5*cdt_subgrid))*F(i,j).Ey(localiIdx,localjIdx) ...
            - (cdt_subgrid/0.25)*F(i  ,j).Bz(localiIdx  ,localjIdx)...
            + (cdt_subgrid/0.25)*F(i-1,j).Bz(localiIdx+1,localjIdx) ...
            );
    end
    localiIdx=2;
    for localjIdx=1:2
       % Updated(i,j)=Updated(i,j)+1;
        F(i,j).Ey(localiIdx,localjIdx)=((0.5*cdt_subgrid)/0.5)*( ...
            (0.5/(0.5*cdt_subgrid))*F(i,j).Ey(localiIdx,localjIdx) ...
            - (cdt_subgrid/MeshFaceAreas.Bz_insideboundary)*F(i  ,j).Bz(localiIdx  ,localjIdx)...
            + (cdt_subgrid/0.25                  )*F(i  ,j).Bz(localiIdx-1,localjIdx) ...
            );
    end
end
j=MeshParam.Fine_Y_to;
localiIdx=1;
localjIdx=1;
% Updated(i,j)=Updated(i,j)+1;
F(i,j).Ey(localiIdx,localjIdx)=((0.5*cdt_subgrid)/0.5)*( ...
    (0.5/(0.5*cdt_subgrid))*F(i,j).Ey(localiIdx,localjIdx) ...
    - (cdt_subgrid/0.25)*F(i  ,j).Bz(localiIdx  ,localjIdx)...
    + (cdt_subgrid/0.25)*F(i-1,j).Bz(localiIdx+1,localjIdx) ...
    );
localjIdx=2;
% Updated(i,j)=Updated(i,j)+1;
F(i,j).Ey(localiIdx,localjIdx)=(MeshFaceAreas.E_insideboundary_larger/0.5)*( ...
    (0.5/MeshFaceAreas.E_insideboundary_larger)*F(i,j).Ey(localiIdx,localjIdx) ...
    - (cdt_subgrid/MeshFaceAreas.Bz_insideboundary)*F(i  ,j).Bz(localiIdx  ,localjIdx)...
    + (cdt_subgrid/MeshFaceAreas.Bz_insideboundary)*F(i-1,j).Bz(localiIdx+1,localjIdx) ...
    );

localiIdx=2;
localjIdx=1;
% Updated(i,j)=Updated(i,j)+1;
F(i,j).Ey(localiIdx,localjIdx)=((0.5*cdt_subgrid)/0.5)*( ...
    (0.5/(0.5*cdt_subgrid))*F(i,j).Ey(localiIdx,localjIdx) ...
    - (cdt_subgrid/MeshFaceAreas.Bz_insideboundary)*F(i  ,j).Bz(localiIdx  ,localjIdx)...
    + (cdt_subgrid/0.25                  )*F(i  ,j).Bz(localiIdx-1,localjIdx) ...
    );
localjIdx=2;
% Updated(i,j)=Updated(i,j)+1;
F(i,j).Ey(localiIdx,localjIdx)=(MeshFaceAreas.E_insideboundary_smaller/0.5)*( ...
    (0.5/MeshFaceAreas.E_insideboundary_smaller)*F(i,j).Ey(localiIdx,localjIdx) ...
    - (cdt_subgrid/MeshFaceAreas.Bz_innercorner   )*F(i  ,j).Bz(localiIdx  ,localjIdx)...
    + (cdt_subgrid/MeshFaceAreas.Bz_insideboundary)*F(i  ,j).Bz(localiIdx-1,localjIdx) ...
    );


i=MeshParam.Fine_X_to+1;

j=MeshParam.Fine_Y_from;
F(i,j).EyPreserve=0;
localiIdx=1;
localjIdx=1;
% Updated(i,j)=Updated(i,j)+1;
F(i,j).Ey(localiIdx,localjIdx)=(MeshFaceAreas.E_innercorner/(sqrt(10)/4.0))*( ...
    ((sqrt(10)/4.0)/MeshFaceAreas.E_innercorner)*F(i,j).Ey(localiIdx,localjIdx) ...
    - (cdt        /MeshFaceAreas.Bz_next2outercorner)*F(i  ,j).Bz ...
    + (cdt_subgrid/MeshFaceAreas.Bz_innercorner     )*F(i-1,j).Bz(2,localjIdx)...
    );
F(i,j).EyPreserve=F(i,j).EyPreserve+F(i,j).Ey(localiIdx,localjIdx);
localjIdx=2;
% Updated(i,j)=Updated(i,j)+1;
F(i,j).Ey(localiIdx,localjIdx)=((0.5*cdt_subgrid)/0.75)*( ...
    (0.75/(0.5*cdt_subgrid))*F(i,j).Ey(localiIdx,localjIdx) ...
    - (cdt        /MeshFaceAreas.Bz_next2outercorner)*F(i  ,j).Bz ...
    + (cdt_subgrid/MeshFaceAreas.Bz_insideboundary  )*F(i-1,j).Bz(2,localjIdx) ...
);
F(i,j).EyPreserve=F(i,j).EyPreserve+F(i,j).Ey(localiIdx,localjIdx);

j=MeshParam.Fine_Y_to;
F(i,j).EyPreserve=0;
localiIdx=1;
localjIdx=1;
% Updated(i,j)=Updated(i,j)+1;
F(i,j).Ey(localiIdx,localjIdx)=((0.5*cdt_subgrid)/0.75)*( ...
    (0.75/(0.5*cdt_subgrid))*F(i,j).Ey(localiIdx,localjIdx) ...
    - (cdt        /MeshFaceAreas.Bz_next2outercorner)*F(i  ,j).Bz ...
    + (cdt_subgrid/MeshFaceAreas.Bz_insideboundary  )*F(i-1,j).Bz(2,localjIdx) ...
    );
F(i,j).EyPreserve=F(i,j).EyPreserve+F(i,j).Ey(localiIdx,localjIdx);
localjIdx=2;
% Updated(i,j)=Updated(i,j)+1;
F(i,j).Ey(localiIdx,localjIdx)=(MeshFaceAreas.E_innercorner/(sqrt(10)/4.0))*( ...
    ((sqrt(10)/4.0)/MeshFaceAreas.E_innercorner)*F(i,j).Ey(localiIdx,localjIdx) ...
    - (cdt        /MeshFaceAreas.Bz_next2outercorner)*F(i  ,j).Bz ...
    + (cdt_subgrid/MeshFaceAreas.Bz_innercorner     )*F(i-1,j).Bz(2        ,localjIdx)...
    );
F(i,j).EyPreserve=F(i,j).EyPreserve+F(i,j).Ey(localiIdx,localjIdx);
for j=MeshParam.Fine_Y_from+1:MeshParam.Fine_Y_to-1
    F(i,j).EyPreserve=0;
    localiIdx=1;
    for localjIdx=1:2
       % Updated(i,j)=Updated(i,j)+1;
        F(i,j).Ey(localiIdx,localjIdx)=((0.5*cdt_subgrid)/0.75)*( ...
            (0.75/(0.5*cdt_subgrid))*F(i,j).Ey(localiIdx,localjIdx) ...
            - (cdt        /MeshFaceAreas.Bz_outsideboundary)*F(i  ,j).Bz...
            + (cdt_subgrid/MeshFaceAreas.Bz_insideboundary )*F(i-1,j).Bz(2,localjIdx) ...
            );
        F(i,j).EyPreserve=F(i,j).EyPreserve+F(i,j).Ey(localiIdx,localjIdx);
    end
end

j=MeshParam.Fine_Y_from;
for i=MeshParam.Fine_X_from+1:MeshParam.Fine_X_to-1
    localiIdx=1;
    localjIdx=1;
   % Updated(i,j)=Updated(i,j)+1;
    F(i,j).Ey(localiIdx,localjIdx)=(MeshFaceAreas.E_insideboundary_larger/0.5)*( ...
        (0.5/MeshFaceAreas.E_insideboundary_larger)*F(i,j).Ey(localiIdx,localjIdx) ...
        - (cdt_subgrid/MeshFaceAreas.Bz_insideboundary)*F(i  ,j).Bz(localiIdx  ,localjIdx)...
        + (cdt_subgrid/MeshFaceAreas.Bz_insideboundary)*F(i-1,j).Bz(localiIdx+1,localjIdx) ...
        );
    localjIdx=2;
   % Updated(i,j)=Updated(i,j)+1;
    F(i,j).Ey(localiIdx,localjIdx)=((0.5*cdt_subgrid)/0.5)*( ...
        (0.5/(0.5*cdt_subgrid))*F(i,j).Ey(localiIdx,localjIdx) ...
        - (cdt_subgrid/0.25)*F(i  ,j).Bz(localiIdx  ,localjIdx)...
        + (cdt_subgrid/0.25)*F(i-1,j).Bz(localiIdx+1,localjIdx) ...
        );
    
    localiIdx=2;
    localjIdx=1;
   % Updated(i,j)=Updated(i,j)+1;
    F(i,j).Ey(localiIdx,localjIdx)=(MeshFaceAreas.E_insideboundary_smaller/0.5)*( ...
        (0.5/MeshFaceAreas.E_insideboundary_smaller)*F(i,j).Ey(localiIdx,localjIdx) ...
        - (cdt_subgrid/MeshFaceAreas.Bz_insideboundary)*F(i  ,j).Bz(localiIdx  ,localjIdx)...
        + (cdt_subgrid/MeshFaceAreas.Bz_insideboundary)*F(i  ,j).Bz(localiIdx-1,localjIdx) ...
        );
    localjIdx=2;
   % Updated(i,j)=Updated(i,j)+1;
    F(i,j).Ey(localiIdx,localjIdx)=((0.5*cdt_subgrid)/0.5)*( ...
        (0.5/(0.5*cdt_subgrid))*F(i,j).Ey(localiIdx,localjIdx) ...
        - (cdt_subgrid/0.25)*F(i  ,j).Bz(localiIdx  ,localjIdx)...
        + (cdt_subgrid/0.25)*F(i  ,j).Bz(localiIdx-1,localjIdx) ...
        );
end
j=MeshParam.Fine_Y_to;
for i=MeshParam.Fine_X_from+1:MeshParam.Fine_X_to-1
    localiIdx=1;
    localjIdx=1;
   % Updated(i,j)=Updated(i,j)+1;
    F(i,j).Ey(localiIdx,localjIdx)=((0.5*cdt_subgrid)/0.5)*( ...
        (0.5/(0.5*cdt_subgrid))*F(i,j).Ey(localiIdx,localjIdx) ...
        - (cdt_subgrid/0.25)*F(i  ,j).Bz(localiIdx  ,localjIdx)...
        + (cdt_subgrid/0.25)*F(i-1,j).Bz(localiIdx+1,localjIdx) ...
        );
    localjIdx=2;
   % Updated(i,j)=Updated(i,j)+1;
    F(i,j).Ey(localiIdx,localjIdx)=(MeshFaceAreas.E_insideboundary_larger/0.5)*( ...
        (0.5/MeshFaceAreas.E_insideboundary_larger)*F(i,j).Ey(localiIdx,localjIdx) ...
        - (cdt_subgrid/MeshFaceAreas.Bz_insideboundary)*F(i  ,j).Bz(localiIdx  ,localjIdx)...
        + (cdt_subgrid/MeshFaceAreas.Bz_insideboundary)*F(i-1,j).Bz(localiIdx+1,localjIdx) ...
        );  
    
    localiIdx=2;
    localjIdx=1;
   % Updated(i,j)=Updated(i,j)+1;
    F(i,j).Ey(localiIdx,localjIdx)=((0.5*cdt_subgrid)/0.5)*( ...
        (0.5/(0.5*cdt_subgrid))*F(i,j).Ey(localiIdx,localjIdx) ...
        - (cdt_subgrid/0.25)*F(i  ,j).Bz(localiIdx  ,localjIdx)...
        + (cdt_subgrid/0.25)*F(i  ,j).Bz(localiIdx-1,localjIdx) ...
        );
    localjIdx=2;
  %  Updated(i,j)=Updated(i,j)+1;
    F(i,j).Ey(localiIdx,localjIdx)=(MeshFaceAreas.E_insideboundary_smaller/0.5)*( ...
        (0.5/MeshFaceAreas.E_insideboundary_smaller)*F(i,j).Ey(localiIdx,localjIdx) ...
        - (cdt_subgrid/MeshFaceAreas.Bz_insideboundary)*F(i  ,j).Bz(localiIdx  ,localjIdx)...
        + (cdt_subgrid/MeshFaceAreas.Bz_insideboundary)*F(i  ,j).Bz(localiIdx-1,localjIdx) ...
        );
end


end

%%
function [F]=Update_E_RegionBoundary_NotFirstTimeSec(F,cdt_subgrid,MeshParam,MeshFaceAreas)
%% update Ex
j=MeshParam.Fine_Y_from;
i=MeshParam.Fine_X_from;
localjIdx=1;
localiIdx=1;
F(i,j).Ex(localiIdx,localjIdx)=(MeshFaceAreas.E_innercorner/(sqrt(10)/4.0))*( ...
    ((sqrt(10)/4.0)/MeshFaceAreas.E_innercorner)*F(i,j).Ex(localiIdx,localjIdx) ...
    + (cdt_subgrid/MeshFaceAreas.Bz_innercorner     )*F(i,j  ).Bz(localiIdx,localjIdx) ...
    );
F(i,j).ExPreserve=F(i,j).ExPreserve+F(i,j).Ex(localiIdx,localjIdx);
localiIdx=2;
F(i,j).Ex(localiIdx,localjIdx)=((0.5*cdt_subgrid)/0.75)*( ...
    (0.75/(0.5*cdt_subgrid))*F(i,j).Ex(localiIdx,localjIdx) ...
    + (cdt_subgrid/MeshFaceAreas.Bz_insideboundary  )*F(i,j  ).Bz(localiIdx,localjIdx) ...
    );
F(i,j).ExPreserve=F(i,j).ExPreserve+F(i,j).Ex(localiIdx,localjIdx);
localjIdx=2;
localiIdx=1;
F(i,j).Ex(localiIdx,localjIdx)=(MeshFaceAreas.E_insideboundary_smaller/0.5)*( ...
    (0.5/MeshFaceAreas.E_insideboundary_smaller)*F(i,j).Ex(localiIdx,localjIdx) ...
    + (cdt_subgrid/MeshFaceAreas.Bz_insideboundary )*F(i,j  ).Bz(localiIdx,localjIdx  ) ...
    - (cdt_subgrid/MeshFaceAreas.Bz_innercorner    )*F(i,j  ).Bz(localiIdx,localjIdx-1)...
    );
localiIdx=2;
F(i,j).Ex(localiIdx,localjIdx)=((0.5*cdt_subgrid)/0.5)*( ...
    (0.5/(0.5*cdt_subgrid))*F(i,j).Ex(localiIdx,localjIdx) ...
    + (cdt_subgrid/0.25                  )*F(i,j  ).Bz(localiIdx,localjIdx  ) ...
    - (cdt_subgrid/MeshFaceAreas.Bz_insideboundary)*F(i,j  ).Bz(localiIdx,localjIdx-1)...
    );

i=MeshParam.Fine_X_to;
localjIdx=1;
localiIdx=1;
F(i,j).Ex(localiIdx,localjIdx)=((0.5*cdt_subgrid)/0.75)*( ...
    (0.75/(0.5*cdt_subgrid))*F(i,j).Ex(localiIdx,localjIdx) ...
    + (cdt_subgrid/MeshFaceAreas.Bz_insideboundary  )*F(i,j  ).Bz(localiIdx,localjIdx) ...
    );
F(i,j).ExPreserve=F(i,j).ExPreserve+F(i,j).Ex(localiIdx,localjIdx);
localiIdx=2;
F(i,j).Ex(localiIdx,localjIdx)=(MeshFaceAreas.E_innercorner/(sqrt(10)/4.0))*( ...
    ((sqrt(10)/4.0)/MeshFaceAreas.E_innercorner)*F(i,j).Ex(localiIdx,localjIdx) ...
    + (cdt_subgrid/MeshFaceAreas.Bz_innercorner     )*F(i,j  ).Bz(localiIdx,localjIdx) ...
    );
F(i,j).ExPreserve=F(i,j).ExPreserve+F(i,j).Ex(localiIdx,localjIdx);
localjIdx=2;
localiIdx=1;
F(i,j).Ex(localiIdx,localjIdx)=((0.5*cdt_subgrid)/0.5)*( ...
    (0.5/(0.5*cdt_subgrid))*F(i,j).Ex(localiIdx,localjIdx) ...
    + (cdt_subgrid/0.25                  )*F(i,j  ).Bz(localiIdx,localjIdx  ) ...
    - (cdt_subgrid/MeshFaceAreas.Bz_insideboundary)*F(i,j  ).Bz(localiIdx,localjIdx-1)...
    );
localiIdx=2;
F(i,j).Ex(localiIdx,localjIdx)=(MeshFaceAreas.E_insideboundary_smaller/0.5)*( ...
    (0.5/MeshFaceAreas.E_insideboundary_smaller)*F(i,j).Ex(localiIdx,localjIdx) ...
    + (cdt_subgrid/MeshFaceAreas.Bz_insideboundary )*F(i,j  ).Bz(localiIdx,localjIdx  ) ...
    - (cdt_subgrid/MeshFaceAreas.Bz_innercorner    )*F(i,j  ).Bz(localiIdx,localjIdx-1)...
    );

for i=MeshParam.Fine_X_from+1:MeshParam.Fine_X_to-1
    for localiIdx=1:2
        localjIdx=1;
        F(i,j).Ex(localiIdx,localjIdx)=((0.5*cdt_subgrid)/0.75)*( ...
            (0.75/(0.5*cdt_subgrid))*F(i,j).Ex(localiIdx,localjIdx) ...
            + (cdt_subgrid/MeshFaceAreas.Bz_insideboundary )*F(i,j  ).Bz(localiIdx,localjIdx) ...
            );
        F(i,j).ExPreserve=F(i,j).ExPreserve+F(i,j).Ex(localiIdx,localjIdx);
        localjIdx=2;
        F(i,j).Ex(localiIdx,localjIdx)=((0.5*cdt_subgrid)/0.5)*( ...
            (0.5/(0.5*cdt_subgrid))*F(i,j).Ex(localiIdx,localjIdx) ...
            + (cdt_subgrid/0.25                  )*F(i,j  ).Bz(localiIdx,localjIdx  ) ...
            - (cdt_subgrid/MeshFaceAreas.Bz_insideboundary)*F(i,j  ).Bz(localiIdx,localjIdx-1)...
            );
    end
end

i=MeshParam.Fine_X_from;
for j=MeshParam.Fine_Y_from+1:MeshParam.Fine_Y_to-1
    localjIdx=1;
    localiIdx=1;
   % Updated(i,j)=Updated(i,j)+1;
    F(i,j).Ex(localiIdx,localjIdx)=(MeshFaceAreas.E_insideboundary_larger/0.5)*( ...
        (0.5/MeshFaceAreas.E_insideboundary_larger)*F(i,j).Ex(localiIdx,localjIdx) ...
        + (cdt_subgrid/MeshFaceAreas.Bz_insideboundary)*F(i,j  ).Bz(localiIdx,localjIdx  )...
        - (cdt_subgrid/MeshFaceAreas.Bz_insideboundary)*F(i,j-1).Bz(localiIdx,localjIdx+1) ...
        );
    localiIdx=2;
   % Updated(i,j)=Updated(i,j)+1;
    F(i,j).Ex(localiIdx,localjIdx)=((0.5*cdt_subgrid)/0.5)*( ...
        (0.5/(0.5*cdt_subgrid))*F(i,j).Ex(localiIdx,localjIdx) ...
        + (cdt_subgrid/0.25)*F(i,j  ).Bz(localiIdx,localjIdx  )...
        - (cdt_subgrid/0.25)*F(i,j-1).Bz(localiIdx,localjIdx+1) ...
        );
    
    localjIdx=2;
    localiIdx=1;
   % Updated(i,j)=Updated(i,j)+1;
    F(i,j).Ex(localiIdx,localjIdx)=(MeshFaceAreas.E_insideboundary_smaller/0.5)*( ...
        (0.5/MeshFaceAreas.E_insideboundary_smaller)*F(i,j).Ex(localiIdx,localjIdx) ...
        + (cdt_subgrid/MeshFaceAreas.Bz_insideboundary)*F(i,j  ).Bz(localiIdx,localjIdx  )...
        - (cdt_subgrid/MeshFaceAreas.Bz_insideboundary)*F(i,j  ).Bz(localiIdx,localjIdx-1) ...
        );
    localiIdx=2;
   % Updated(i,j)=Updated(i,j)+1;
    F(i,j).Ex(localiIdx,localjIdx)=((0.5*cdt_subgrid)/0.5)*( ...
        (0.5/(0.5*cdt_subgrid))*F(i,j).Ex(localiIdx,localjIdx) ...
        + (cdt_subgrid/0.25)*F(i,j  ).Bz(localiIdx,localjIdx  )...
        - (cdt_subgrid/0.25)*F(i,j  ).Bz(localiIdx,localjIdx-1) ...
        );
end

i=MeshParam.Fine_X_to;
for j=MeshParam.Fine_Y_from+1:MeshParam.Fine_Y_to-1
    localjIdx=1;
    localiIdx =1;
    F(i,j).Ex(localiIdx,localjIdx)=((0.5*cdt_subgrid)/0.5)*( ...
        (0.5/(0.5*cdt_subgrid))*F(i,j).Ex(localiIdx,localjIdx) ...
        + (cdt_subgrid/0.25                  )*F(i,j  ).Bz(localiIdx,localjIdx  ) ...
        - (cdt_subgrid/0.25                  )*F(i,j-1).Bz(localiIdx,localjIdx+1)...
        );
    localiIdx =2;
    F(i,j).Ex(localiIdx,localjIdx)=(MeshFaceAreas.E_insideboundary_larger/0.5)*( ...
        (0.5/MeshFaceAreas.E_insideboundary_larger)*F(i,j).Ex(localiIdx,localjIdx) ...
        + (cdt_subgrid/MeshFaceAreas.Bz_insideboundary)*F(i,j  ).Bz(localiIdx,localjIdx  ) ...
        - (cdt_subgrid/MeshFaceAreas.Bz_insideboundary)*F(i,j-1).Bz(localiIdx,localjIdx+1)...
        );
    
    localjIdx=2;
    localiIdx =1;
    F(i,j).Ex(localiIdx,localjIdx)=((0.5*cdt_subgrid)/0.5)*( ...
        (0.5/(0.5*cdt_subgrid))*F(i,j).Ex(localiIdx,localjIdx) ...
        + (cdt_subgrid/0.25                  )*F(i,j  ).Bz(localiIdx,localjIdx  ) ...
        - (cdt_subgrid/0.25                  )*F(i,j  ).Bz(localiIdx,localjIdx-1)...
        );
    localiIdx =2;
    F(i,j).Ex(localiIdx,localjIdx)=(MeshFaceAreas.E_insideboundary_smaller/0.5)*( ...
        (0.5/MeshFaceAreas.E_insideboundary_smaller)*F(i,j).Ex(localiIdx,localjIdx) ...
        + (cdt_subgrid/MeshFaceAreas.Bz_insideboundary)*F(i,j  ).Bz(localiIdx,localjIdx  ) ...
        - (cdt_subgrid/MeshFaceAreas.Bz_insideboundary)*F(i,j  ).Bz(localiIdx,localjIdx-1)...
        );
end

j=MeshParam.Fine_Y_to;
i=MeshParam.Fine_X_from;
localjIdx=1;
localiIdx=1;
% Updated(i,j)=Updated(i,j)+1;
F(i,j).Ex(localiIdx,localjIdx)=(MeshFaceAreas.E_insideboundary_larger/0.5)*( ...
    (0.5/MeshFaceAreas.E_insideboundary_larger)*F(i,j).Ex(localiIdx,localjIdx) ...
    + (cdt_subgrid/MeshFaceAreas.Bz_insideboundary)*F(i,j  ).Bz(localiIdx,localjIdx  )...
    - (cdt_subgrid/MeshFaceAreas.Bz_insideboundary)*F(i,j-1).Bz(localiIdx,localjIdx+1) ...
    );
localiIdx=2;
% Updated(i,j)=Updated(i,j)+1;
F(i,j).Ex(localiIdx,localjIdx)=((0.5*cdt_subgrid)/0.5)*( ...
    (0.5/(0.5*cdt_subgrid))*F(i,j).Ex(localiIdx,localjIdx) ...
    + (cdt_subgrid/0.25)*F(i,j  ).Bz(localiIdx,localjIdx  )...
    - (cdt_subgrid/0.25)*F(i,j-1).Bz(localiIdx,localjIdx+1) ...
    );
localjIdx=2;
localiIdx=1;
% Updated(i,j)=Updated(i,j)+1;
F(i,j).Ex(localiIdx,localjIdx)=(MeshFaceAreas.E_insideboundary_smaller/0.5)*( ...
    (0.5/MeshFaceAreas.E_insideboundary_smaller)*F(i,j).Ex(localiIdx,localjIdx) ...
    + (cdt_subgrid/MeshFaceAreas.Bz_innercorner   )*F(i,j  ).Bz(localiIdx,localjIdx  )...
    - (cdt_subgrid/MeshFaceAreas.Bz_insideboundary)*F(i,j  ).Bz(localiIdx,localjIdx-1) ...
    );
localiIdx=2;
% Updated(i,j)=Updated(i,j)+1;
F(i,j).Ex(localiIdx,localjIdx)=((0.5*cdt_subgrid)/0.5)*( ...
    (0.5/(0.5*cdt_subgrid))*F(i,j).Ex(localiIdx,localjIdx) ...
    + (cdt_subgrid/MeshFaceAreas.Bz_insideboundary)*F(i,j  ).Bz(localiIdx,localjIdx  )...
    - (cdt_subgrid/0.25                  )*F(i,j  ).Bz(localiIdx,localjIdx-1) ...
    );


j=MeshParam.Fine_Y_to;
for i=MeshParam.Fine_X_from+1:MeshParam.Fine_X_to-1
    localjIdx=1;
    for localiIdx =1:2
        F(i,j).Ex(localiIdx,localjIdx)=((0.5*cdt_subgrid)/0.5)*( ...
            (0.5/(0.5*cdt_subgrid))*F(i,j).Ex(localiIdx,localjIdx) ...
            + (cdt_subgrid/0.25                  )*F(i,j  ).Bz(localiIdx,localjIdx  ) ...
            - (cdt_subgrid/0.25                  )*F(i,j-1).Bz(localiIdx,localjIdx+1)...
            );    
    end
    localjIdx=2;
    for localiIdx =1:2                
        F(i,j).Ex(localiIdx,localjIdx)=((0.5*cdt_subgrid)/0.5)*( ...
            (0.5/(0.5*cdt_subgrid))*F(i,j).Ex(localiIdx,localjIdx) ...
            + (cdt_subgrid/MeshFaceAreas.Bz_insideboundary)*F(i,j  ).Bz(localiIdx,localjIdx  ) ...
            - (cdt_subgrid/0.25                  )*F(i,j  ).Bz(localiIdx,localjIdx-1)...
            );
    end
end

j=MeshParam.Fine_Y_to;
i=MeshParam.Fine_X_to;
localjIdx = 1;
localiIdx = 1;
F(i,j).Ex(localiIdx,localjIdx)=((0.5*cdt_subgrid)/0.5)*( ...
    (0.5/(0.5*cdt_subgrid))*F(i,j).Ex(localiIdx,localjIdx) ...
    + (cdt_subgrid/0.25                  )*F(i,j  ).Bz(localiIdx,localjIdx  ) ...
    - (cdt_subgrid/0.25                  )*F(i,j-1).Bz(localiIdx,localjIdx+1)...
    );
localiIdx = 2;
F(i,j).Ex(localiIdx,localjIdx)=(MeshFaceAreas.E_insideboundary_larger/0.5)*( ...
    (0.5/MeshFaceAreas.E_insideboundary_larger)*F(i,j).Ex(localiIdx,localjIdx) ...
    + (cdt_subgrid/MeshFaceAreas.Bz_insideboundary)*F(i,j  ).Bz(localiIdx,localjIdx  ) ...
    - (cdt_subgrid/MeshFaceAreas.Bz_insideboundary)*F(i,j-1).Bz(localiIdx,localjIdx+1)...
    );
localjIdx=2;
localiIdx =1;
F(i,j).Ex(localiIdx,localjIdx)=((0.5*cdt_subgrid)/0.5)*( ...
    (0.5/(0.5*cdt_subgrid))*F(i,j).Ex(localiIdx,localjIdx) ...
    + (cdt_subgrid/MeshFaceAreas.Bz_insideboundary)*F(i,j  ).Bz(localiIdx,localjIdx  ) ...
    - (cdt_subgrid/0.25                  )*F(i,j  ).Bz(localiIdx,localjIdx-1)...
    );
localiIdx =2;
F(i,j).Ex(localiIdx,localjIdx)=(MeshFaceAreas.E_insideboundary_smaller/0.5)*( ...
    (0.5/MeshFaceAreas.E_insideboundary_smaller)*F(i,j).Ex(localiIdx,localjIdx) ...
    + (cdt_subgrid/MeshFaceAreas.Bz_innercorner   )*F(i,j  ).Bz(localiIdx,localjIdx  ) ...
    - (cdt_subgrid/MeshFaceAreas.Bz_insideboundary)*F(i,j  ).Bz(localiIdx,localjIdx-1)...
    );

j=MeshParam.Fine_Y_to+1;
i=MeshParam.Fine_X_from;
localjIdx=1;
localiIdx=1;
F(i,j).Ex(localiIdx,localjIdx)=(MeshFaceAreas.E_innercorner/(sqrt(10)/4.0))*( ...
    ((sqrt(10)/4.0)/MeshFaceAreas.E_innercorner)*F(i,j).Ex(localiIdx,localjIdx) ...
    - (cdt_subgrid/MeshFaceAreas.Bz_innercorner     )*F(i,j-1).Bz(localiIdx,2        )...
    );
F(i,j).ExPreserve=F(i,j).ExPreserve+F(i,j).Ex(localiIdx,localjIdx);
localiIdx=2;
F(i,j).Ex(localiIdx,localjIdx)=((0.5*cdt_subgrid)/0.75)*( ...
    (0.75/(0.5*cdt_subgrid))*F(i,j).Ex(localiIdx,localjIdx) ...
    - (cdt_subgrid/MeshFaceAreas.Bz_insideboundary  )*F(i,j-1).Bz(localiIdx,2        ) ...
);
F(i,j).ExPreserve=F(i,j).ExPreserve+F(i,j).Ex(localiIdx,localjIdx);

i=MeshParam.Fine_X_to;
localjIdx=1;
localiIdx=1;
F(i,j).Ex(localiIdx,localjIdx)=((0.5*cdt_subgrid)/0.75)*( ...
    (0.75/(0.5*cdt_subgrid))*F(i,j).Ex(localiIdx,localjIdx) ...
    - (cdt_subgrid/MeshFaceAreas.Bz_insideboundary  )*F(i,j-1).Bz(localiIdx,2        ) ...
);
F(i,j).ExPreserve=F(i,j).ExPreserve+F(i,j).Ex(localiIdx,localjIdx);
localiIdx=2;
F(i,j).Ex(localiIdx,localjIdx)=(MeshFaceAreas.E_innercorner/(sqrt(10)/4.0))*( ...
    ((sqrt(10)/4.0)/MeshFaceAreas.E_innercorner)*F(i,j).Ex(localiIdx,localjIdx) ...
    - (cdt_subgrid/MeshFaceAreas.Bz_innercorner     )*F(i,j-1).Bz(localiIdx,2        )...
    );
F(i,j).ExPreserve=F(i,j).ExPreserve+F(i,j).Ex(localiIdx,localjIdx);

for i=MeshParam.Fine_X_from+1:MeshParam.Fine_X_to-1
    localjIdx=1;
    for localiIdx=1:2
        F(i,j).Ex(localiIdx,localjIdx)=((0.5*cdt_subgrid)/0.75)*( ...
            (0.75/(0.5*cdt_subgrid))*F(i,j).Ex(localiIdx,localjIdx) ...
            - (cdt_subgrid/MeshFaceAreas.Bz_insideboundary )*F(i,j-1).Bz(localiIdx,2) ...
            );
        F(i,j).ExPreserve=F(i,j).ExPreserve+F(i,j).Ex(localiIdx,localjIdx);
    end
end

%% update Ey
i=MeshParam.Fine_X_from;
j=MeshParam.Fine_Y_from;
localiIdx=1;
localjIdx=1;
F(i,j).Ey(localiIdx,localjIdx)=(MeshFaceAreas.E_innercorner/(sqrt(10)/4.0))*( ...
    ((sqrt(10)/4.0)/MeshFaceAreas.E_innercorner)*F(i,j).Ey(localiIdx,localjIdx) ...
    - (cdt_subgrid/MeshFaceAreas.Bz_innercorner     )*F(i  ,j).Bz(localiIdx,localjIdx) ...
    );
F(i,j).EyPreserve=F(i,j).EyPreserve+F(i,j).Ey(localiIdx,localjIdx);
localjIdx=2;
F(i,j).Ey(localiIdx,localjIdx)=((0.5*cdt_subgrid)/0.75)*( ...
    (0.75/(0.5*cdt_subgrid))*F(i,j).Ey(localiIdx,localjIdx) ...
    - (cdt_subgrid/MeshFaceAreas.Bz_insideboundary  )*F(i  ,j).Bz(localiIdx,localjIdx) ...
    );
F(i,j).EyPreserve=F(i,j).EyPreserve+F(i,j).Ey(localiIdx,localjIdx);
localiIdx=2;
localjIdx=1;
F(i,j).Ey(localiIdx,localjIdx)=(MeshFaceAreas.E_insideboundary_smaller/0.5)*( ...
    (0.5/MeshFaceAreas.E_insideboundary_smaller)*F(i,j).Ey(localiIdx,localjIdx) ...
    - (cdt_subgrid/MeshFaceAreas.Bz_insideboundary )*F(i  ,j).Bz(localiIdx  ,localjIdx) ...
    + (cdt_subgrid/MeshFaceAreas.Bz_innercorner    )*F(i  ,j).Bz(localiIdx-1,localjIdx)...
    );
localjIdx=2;
F(i,j).Ey(localiIdx,localjIdx)=((0.5*cdt_subgrid)/0.5)*( ...
    (0.5/(0.5*cdt_subgrid))*F(i,j).Ey(localiIdx,localjIdx) ...
    - (cdt_subgrid/0.25                  )*F(i  ,j).Bz(localiIdx  ,localjIdx) ...
    + (cdt_subgrid/MeshFaceAreas.Bz_insideboundary)*F(i  ,j).Bz(localiIdx-1,localjIdx)...
    );

j=MeshParam.Fine_Y_to;
localiIdx=1;
localjIdx=1;
F(i,j).Ey(localiIdx,localjIdx)=((0.5*cdt_subgrid)/0.75)*( ...
    (0.75/(0.5*cdt_subgrid))*F(i,j).Ey(localiIdx,localjIdx) ...
    - (cdt_subgrid/MeshFaceAreas.Bz_insideboundary  )*F(i  ,j).Bz(localiIdx,localjIdx) ...
    );
F(i,j).EyPreserve=F(i,j).EyPreserve+F(i,j).Ey(localiIdx,localjIdx);
localjIdx=2;
F(i,j).Ey(localiIdx,localjIdx)=(MeshFaceAreas.E_innercorner/(sqrt(10)/4.0))*( ...
    ((sqrt(10)/4.0)/MeshFaceAreas.E_innercorner)*F(i,j).Ey(localiIdx,localjIdx) ...
    - (cdt_subgrid/MeshFaceAreas.Bz_innercorner     )*F(i  ,j).Bz(localiIdx,localjIdx) ...
    );
F(i,j).EyPreserve=F(i,j).EyPreserve+F(i,j).Ey(localiIdx,localjIdx);
localiIdx=2;
localjIdx=1;
F(i,j).Ey(localiIdx,localjIdx)=((0.5*cdt_subgrid)/0.5)*( ...
    (0.5/(0.5*cdt_subgrid))*F(i,j).Ey(localiIdx,localjIdx) ...
    - (cdt_subgrid/0.25                  )*F(i  ,j).Bz(localiIdx  ,localjIdx) ...
    + (cdt_subgrid/MeshFaceAreas.Bz_insideboundary)*F(i  ,j).Bz(localiIdx-1,localjIdx)...
    );
localjIdx=2;
F(i,j).Ey(localiIdx,localjIdx)=(MeshFaceAreas.E_insideboundary_smaller/0.5)*( ...
    (0.5/MeshFaceAreas.E_insideboundary_smaller)*F(i,j).Ey(localiIdx,localjIdx) ...
    - (cdt_subgrid/MeshFaceAreas.Bz_insideboundary )*F(i  ,j).Bz(localiIdx  ,localjIdx) ...
    + (cdt_subgrid/MeshFaceAreas.Bz_innercorner    )*F(i  ,j).Bz(localiIdx-1,localjIdx)...
    );

for j=MeshParam.Fine_Y_from+1:MeshParam.Fine_Y_to-1
    for localjIdx=1:2
        localiIdx=1;
        F(i,j).Ey(localiIdx,localjIdx)=((0.5*cdt_subgrid)/0.75)*( ...
            (0.75/(0.5*cdt_subgrid))*F(i,j).Ey(localiIdx,localjIdx) ...
            - (cdt_subgrid/MeshFaceAreas.Bz_insideboundary )*F(i  ,j).Bz(localiIdx,localjIdx) ...
            );
        F(i,j).EyPreserve=F(i,j).EyPreserve+F(i,j).Ey(localiIdx,localjIdx);
        localiIdx=2;
        F(i,j).Ey(localiIdx,localjIdx)=((0.5*cdt_subgrid)/0.5)*( ...
            (0.5/(0.5*cdt_subgrid))*F(i,j).Ey(localiIdx,localjIdx) ...
            - (cdt_subgrid/0.25                  )*F(i  ,j).Bz(localiIdx  ,localjIdx) ...
            + (cdt_subgrid/MeshFaceAreas.Bz_insideboundary)*F(i  ,j).Bz(localiIdx-1,localjIdx)...
            );
    end
end

j=MeshParam.Fine_Y_from;
for i=MeshParam.Fine_X_from+1:MeshParam.Fine_X_to-1
    localiIdx=1;
    localjIdx=1;
   % Updated(i,j)=Updated(i,j)+1;
    F(i,j).Ey(localiIdx,localjIdx)=(MeshFaceAreas.E_insideboundary_larger/0.5)*( ...
        (0.5/MeshFaceAreas.E_insideboundary_larger)*F(i,j).Ey(localiIdx,localjIdx) ...
        - (cdt_subgrid/MeshFaceAreas.Bz_insideboundary)*F(i  ,j).Bz(localiIdx  ,localjIdx)...
        + (cdt_subgrid/MeshFaceAreas.Bz_insideboundary)*F(i-1,j).Bz(localiIdx+1,localjIdx) ...
        );
    localjIdx=2;
   % Updated(i,j)=Updated(i,j)+1;
    F(i,j).Ey(localiIdx,localjIdx)=((0.5*cdt_subgrid)/0.5)*( ...
        (0.5/(0.5*cdt_subgrid))*F(i,j).Ey(localiIdx,localjIdx) ...
        - (cdt_subgrid/0.25)*F(i  ,j).Bz(localiIdx  ,localjIdx)...
        + (cdt_subgrid/0.25)*F(i-1,j).Bz(localiIdx+1,localjIdx) ...
        );
    
    localiIdx=2;
    localjIdx=1;
   % Updated(i,j)=Updated(i,j)+1;
    F(i,j).Ey(localiIdx,localjIdx)=(MeshFaceAreas.E_insideboundary_smaller/0.5)*( ...
        (0.5/MeshFaceAreas.E_insideboundary_smaller)*F(i,j).Ey(localiIdx,localjIdx) ...
        - (cdt_subgrid/MeshFaceAreas.Bz_insideboundary)*F(i  ,j).Bz(localiIdx  ,localjIdx)...
        + (cdt_subgrid/MeshFaceAreas.Bz_insideboundary)*F(i  ,j).Bz(localiIdx-1,localjIdx) ...
        );
    localjIdx=2;
   % Updated(i,j)=Updated(i,j)+1;
    F(i,j).Ey(localiIdx,localjIdx)=((0.5*cdt_subgrid)/0.5)*( ...
        (0.5/(0.5*cdt_subgrid))*F(i,j).Ey(localiIdx,localjIdx) ...
        - (cdt_subgrid/0.25)*F(i  ,j).Bz(localiIdx  ,localjIdx)...
        + (cdt_subgrid/0.25)*F(i  ,j).Bz(localiIdx-1,localjIdx) ...
        );
end



j=MeshParam.Fine_Y_to;
for i=MeshParam.Fine_X_from+1:MeshParam.Fine_X_to-1
    localiIdx=1;
    localjIdx =1;
    F(i,j).Ey(localiIdx,localjIdx)=((0.5*cdt_subgrid)/0.5)*( ...
        (0.5/(0.5*cdt_subgrid))*F(i,j).Ey(localiIdx,localjIdx) ...
        - (cdt_subgrid/0.25                  )*F(i  ,j).Bz(localiIdx  ,localjIdx) ...
        + (cdt_subgrid/0.25                  )*F(i-1,j).Bz(localiIdx+1,localjIdx)...
        );
    localjIdx =2;
    F(i,j).Ey(localiIdx,localjIdx)=(MeshFaceAreas.E_insideboundary_larger/0.5)*( ...
        (0.5/MeshFaceAreas.E_insideboundary_larger)*F(i,j).Ey(localiIdx,localjIdx) ...
        - (cdt_subgrid/MeshFaceAreas.Bz_insideboundary)*F(i  ,j).Bz(localiIdx  ,localjIdx) ...
        + (cdt_subgrid/MeshFaceAreas.Bz_insideboundary)*F(i-1,j).Bz(localiIdx+1,localjIdx)...
        );
    
    localiIdx=2;
    localjIdx =1;
    F(i,j).Ey(localiIdx,localjIdx)=((0.5*cdt_subgrid)/0.5)*( ...
        (0.5/(0.5*cdt_subgrid))*F(i,j).Ey(localiIdx,localjIdx) ...
        - (cdt_subgrid/0.25                  )*F(i  ,j).Bz(localiIdx  ,localjIdx) ...
        + (cdt_subgrid/0.25                  )*F(i  ,j).Bz(localiIdx-1,localjIdx)...
        );
    localjIdx =2;
    F(i,j).Ey(localiIdx,localjIdx)=(MeshFaceAreas.E_insideboundary_smaller/0.5)*( ...
        (0.5/MeshFaceAreas.E_insideboundary_smaller)*F(i,j).Ey(localiIdx,localjIdx) ...
        - (cdt_subgrid/MeshFaceAreas.Bz_insideboundary)*F(i,j  ).Bz(localiIdx,localjIdx  ) ...
        + (cdt_subgrid/MeshFaceAreas.Bz_insideboundary)*F(i,j  ).Bz(localiIdx,localjIdx-1)...
        );
end
i=MeshParam.Fine_X_to;
j=MeshParam.Fine_Y_from;
localiIdx=1;
localjIdx=1;
% Updated(i,j)=Updated(i,j)+1;
F(i,j).Ey(localiIdx,localjIdx)=(MeshFaceAreas.E_insideboundary_larger/0.5)*( ...
    (0.5/MeshFaceAreas.E_insideboundary_larger)*F(i,j).Ey(localiIdx,localjIdx) ...
    - (cdt_subgrid/MeshFaceAreas.Bz_insideboundary)*F(i  ,j).Bz(localiIdx  ,localjIdx)...
    + (cdt_subgrid/MeshFaceAreas.Bz_insideboundary)*F(i-1,j).Bz(localiIdx+1,localjIdx) ...
    );
localjIdx=2;
% Updated(i,j)=Updated(i,j)+1;
F(i,j).Ey(localiIdx,localjIdx)=((0.5*cdt_subgrid)/0.5)*( ...
    (0.5/(0.5*cdt_subgrid))*F(i,j).Ey(localiIdx,localjIdx) ...
    - (cdt_subgrid/0.25)*F(i  ,j).Bz(localiIdx  ,localjIdx)...
    + (cdt_subgrid/0.25)*F(i-1,j).Bz(localiIdx+1,localjIdx) ...
    );
localiIdx=2;
localjIdx=1;
% Updated(i,j)=Updated(i,j)+1;
F(i,j).Ey(localiIdx,localjIdx)=(MeshFaceAreas.E_insideboundary_smaller/0.5)*( ...
    (0.5/MeshFaceAreas.E_insideboundary_smaller)*F(i,j).Ey(localiIdx,localjIdx) ...
    - (cdt_subgrid/MeshFaceAreas.Bz_innercorner   )*F(i  ,j).Bz(localiIdx  ,localjIdx)...
    + (cdt_subgrid/MeshFaceAreas.Bz_insideboundary)*F(i  ,j).Bz(localiIdx-1,localjIdx) ...
    );
localjIdx=2;
% Updated(i,j)=Updated(i,j)+1;
F(i,j).Ey(localiIdx,localjIdx)=((0.5*cdt_subgrid)/0.5)*( ...
    (0.5/(0.5*cdt_subgrid))*F(i,j).Ey(localiIdx,localjIdx) ...
    - (cdt_subgrid/MeshFaceAreas.Bz_insideboundary)*F(i  ,j).Bz(localiIdx  ,localjIdx)...
    + (cdt_subgrid/0.25                  )*F(i  ,j).Bz(localiIdx-1,localjIdx) ...
    );


i=MeshParam.Fine_X_to;
for j=MeshParam.Fine_Y_from+1:MeshParam.Fine_Y_to-1
    localiIdx=1;
    for localjIdx =1:2
        F(i,j).Ey(localiIdx,localjIdx)=((0.5*cdt_subgrid)/0.5)*( ...
            (0.5/(0.5*cdt_subgrid))*F(i,j).Ey(localiIdx,localjIdx) ...
            - (cdt_subgrid/0.25                  )*F(i  ,j).Bz(localiIdx  ,localjIdx) ...
            + (cdt_subgrid/0.25                  )*F(i-1,j).Bz(localiIdx+1,localjIdx)...
            );    
    end
    localiIdx=2;
    for localjIdx =1:2                
        F(i,j).Ey(localiIdx,localjIdx)=((0.5*cdt_subgrid)/0.5)*( ...
            (0.5/(0.5*cdt_subgrid))*F(i,j).Ey(localiIdx,localjIdx) ...
            - (cdt_subgrid/MeshFaceAreas.Bz_insideboundary)*F(i  ,j).Bz(localiIdx  ,localjIdx) ...
            + (cdt_subgrid/0.25                  )*F(i  ,j).Bz(localiIdx-1,localjIdx)...
            );
    end
end

j=MeshParam.Fine_Y_to;
i=MeshParam.Fine_X_to;
localiIdx = 1;
localjIdx = 1;
F(i,j).Ey(localiIdx,localjIdx)=((0.5*cdt_subgrid)/0.5)*( ...
    (0.5/(0.5*cdt_subgrid))*F(i,j).Ey(localiIdx,localjIdx) ...
    - (cdt_subgrid/0.25                  )*F(i  ,j).Bz(localiIdx  ,localjIdx) ...
    + (cdt_subgrid/0.25                  )*F(i-1,j).Bz(localiIdx+1,localjIdx)...
    );
localjIdx = 2;
F(i,j).Ey(localiIdx,localjIdx)=(MeshFaceAreas.E_insideboundary_larger/0.5)*( ...
    (0.5/MeshFaceAreas.E_insideboundary_larger)*F(i,j).Ey(localiIdx,localjIdx) ...
    - (cdt_subgrid/MeshFaceAreas.Bz_insideboundary)*F(i  ,j).Bz(localiIdx  ,localjIdx) ...
    + (cdt_subgrid/MeshFaceAreas.Bz_insideboundary)*F(i-1,j).Bz(localiIdx+1,localjIdx)...
    );
localiIdx=2;
localjIdx =1;
F(i,j).Ey(localiIdx,localjIdx)=((0.5*cdt_subgrid)/0.5)*( ...
    (0.5/(0.5*cdt_subgrid))*F(i,j).Ey(localiIdx,localjIdx) ...
    - (cdt_subgrid/MeshFaceAreas.Bz_insideboundary)*F(i  ,j).Bz(localiIdx  ,localjIdx) ...
    + (cdt_subgrid/0.25                  )*F(i  ,j).Bz(localiIdx-1,localjIdx)...
    );
localjIdx =2;
F(i,j).Ey(localiIdx,localjIdx)=(MeshFaceAreas.E_insideboundary_smaller/0.5)*( ...
    (0.5/MeshFaceAreas.E_insideboundary_smaller)*F(i,j).Ey(localiIdx,localjIdx) ...
    - (cdt_subgrid/MeshFaceAreas.Bz_innercorner   )*F(i  ,j).Bz(localiIdx  ,localjIdx) ...
    + (cdt_subgrid/MeshFaceAreas.Bz_insideboundary)*F(i  ,j).Bz(localiIdx-1,localjIdx)...
    );

i=MeshParam.Fine_X_to+1;
j=MeshParam.Fine_Y_from;
localiIdx=1;
localjIdx=1;
F(i,j).Ey(localiIdx,localjIdx)=(MeshFaceAreas.E_innercorner/(sqrt(10)/4.0))*( ...
    ((sqrt(10)/4.0)/MeshFaceAreas.E_innercorner)*F(i,j).Ey(localiIdx,localjIdx) ...
    + (cdt_subgrid/MeshFaceAreas.Bz_innercorner     )*F(i-1,j).Bz(2        ,localjIdx)...
    );
F(i,j).EyPreserve=F(i,j).EyPreserve+F(i,j).Ey(localiIdx,localjIdx);
localjIdx=2;
F(i,j).Ey(localiIdx,localjIdx)=((0.5*cdt_subgrid)/0.75)*( ...
    (0.75/(0.5*cdt_subgrid))*F(i,j).Ey(localiIdx,localjIdx) ...
    + (cdt_subgrid/MeshFaceAreas.Bz_insideboundary  )*F(i-1,j).Bz(2        ,localjIdx) ...
);
F(i,j).EyPreserve=F(i,j).EyPreserve+F(i,j).Ey(localiIdx,localjIdx);

j=MeshParam.Fine_Y_to;
localiIdx=1;
localjIdx=1;
F(i,j).Ey(localiIdx,localjIdx)=((0.5*cdt_subgrid)/0.75)*( ...
    (0.75/(0.5*cdt_subgrid))*F(i,j).Ey(localiIdx,localjIdx) ...
    + (cdt_subgrid/MeshFaceAreas.Bz_insideboundary  )*F(i-1,j).Bz(2        ,localjIdx) ...
);
F(i,j).EyPreserve=F(i,j).EyPreserve+F(i,j).Ey(localiIdx,localjIdx);
localjIdx=2;
F(i,j).Ey(localiIdx,localjIdx)=(MeshFaceAreas.E_innercorner/(sqrt(10)/4.0))*( ...
    ((sqrt(10)/4.0)/MeshFaceAreas.E_innercorner)*F(i,j).Ey(localiIdx,localjIdx) ...
    + (cdt_subgrid/MeshFaceAreas.Bz_innercorner     )*F(i-1,j).Bz(2        ,localjIdx)...
    );
F(i,j).EyPreserve=F(i,j).EyPreserve+F(i,j).Ey(localiIdx,localjIdx);

for j=MeshParam.Fine_Y_from+1:MeshParam.Fine_Y_to-1
    localiIdx=1;
    for localjIdx=1:2
        F(i,j).Ey(localiIdx,localjIdx)=((0.5*cdt_subgrid)/0.75)*( ...
            (0.75/(0.5*cdt_subgrid))*F(i,j).Ey(localiIdx,localjIdx) ...
            + (cdt_subgrid/MeshFaceAreas.Bz_insideboundary )*F(i-1,j).Bz(2,localiIdx) ...
            );
        F(i,j).EyPreserve=F(i,j).EyPreserve+F(i,j).Ey(localiIdx,localjIdx);
    end
end

end

%%
function [F]=Update_E_FineRegion(F,cdt_subgrid,MeshParam)

for j=MeshParam.Fine_Y_from+1:MeshParam.Fine_Y_to-1
    for i=MeshParam.Fine_X_from+1:MeshParam.Fine_X_to-1
        localjIdx=1;
        for localiIdx =1:2
            F(i,j).Ex(localiIdx,localjIdx)=((0.5*cdt_subgrid)/0.5)*( ...
                (0.5/(0.5*cdt_subgrid))*F(i,j).Ex(localiIdx,localjIdx) ...
                + (cdt_subgrid/0.25)*F(i,j  ).Bz(localiIdx,localjIdx  ) ...
                - (cdt_subgrid/0.25)*F(i,j-1).Bz(localiIdx,localjIdx+1)...
                );
        end
        localjIdx=2;
        for localiIdx =1:2
            F(i,j).Ex(localiIdx,localjIdx)=((0.5*cdt_subgrid)/0.5)*( ...
                (0.5/(0.5*cdt_subgrid))*F(i,j).Ex(localiIdx,localjIdx) ...
                + (cdt_subgrid/0.25)*F(i,j  ).Bz(localiIdx,localjIdx  ) ...
                - (cdt_subgrid/0.25)*F(i,j  ).Bz(localiIdx,localjIdx-1)...
                );
        end     
    end
end

for j=MeshParam.Fine_Y_from+1:MeshParam.Fine_Y_to-1
    for i=MeshParam.Fine_X_from+1:MeshParam.Fine_X_to-1
        localiIdx=1;
        for localjIdx =1:2
            F(i,j).Ey(localiIdx,localjIdx)=((0.5*cdt_subgrid)/0.5)*( ...
                (0.5/(0.5*cdt_subgrid))*F(i,j).Ey(localiIdx,localjIdx) ...
                - (cdt_subgrid/0.25)*F(i  ,j).Bz(localiIdx  ,localjIdx) ...
                + (cdt_subgrid/0.25)*F(i-1,j).Bz(localiIdx+1,localjIdx)...
                );
        end
        localiIdx=2;
        for localjIdx =1:2
            F(i,j).Ey(localiIdx,localjIdx)=((0.5*cdt_subgrid)/0.5)*( ...
                (0.5/(0.5*cdt_subgrid))*F(i,j).Ey(localiIdx,localjIdx) ...
                - (cdt_subgrid/0.25)*F(i  ,j).Bz(localiIdx  ,localjIdx) ...
                + (cdt_subgrid/0.25)*F(i  ,j).Bz(localiIdx-1,localjIdx)...
                );
        end     
    end
end


end


%%
function [F,Updated]=Update_Bz_CoarseRegion(F,MeshParam,Updated)
for j=1:MeshParam.Fine_Y_from-2
    for i=1:MeshParam.Size_X-1
       % Updated(i,j)=Updated(i,j)+1;
        F(i,j).Bz=F(i,j).Bz ...
            -F(i  ,j  ).Ex+F(i  ,j+1).Ex ...
            +F(i  ,j  ).Ey-F(i+1,j  ).Ey;
    end
    i=MeshParam.Size_X;
   % Updated(i,j)=Updated(i,j)+1;
    F(i,j).Bz=F(i,j).Bz ...
        -F(i  ,j  ).Ex+F(i  ,j+1).Ex ...
        +F(i  ,j  ).Ey-F(1  ,j  ).Ey;
end

for j=MeshParam.Fine_Y_from-1:MeshParam.Fine_Y_to+1
    for i=1:MeshParam.Fine_X_from-2
       % Updated(i,j)=Updated(i,j)+1;
        F(i,j).Bz=F(i,j).Bz ...
            -F(i  ,j  ).Ex+F(i  ,j+1).Ex ...
            +F(i  ,j  ).Ey-F(i+1,j  ).Ey;
    end
end

j=MeshParam.Fine_Y_from-1;
for i=MeshParam.Fine_X_from-1:(MeshParam.Fine_X_to+1)-(MeshParam.Fine_X_from-1):MeshParam.Fine_X_to+1
   % Updated(i,j)=Updated(i,j)+1;
    F(i,j).Bz=F(i,j).Bz ...
        -F(i  ,j  ).Ex+F(i  ,j+1).Ex ...
        +F(i  ,j  ).Ey-F(i+1,j  ).Ey;
end
for i=MeshParam.Fine_X_from:MeshParam.Fine_X_to
   % Updated(i,j)=Updated(i,j)+1;
    F(i,j).Bz=F(i,j).Bz ...
        -F(i  ,j  ).Ex+F(i  ,j+1).ExPreserve ...
        +F(i  ,j  ).Ey-F(i+1,j  ).Ey;
end

i=MeshParam.Fine_X_from-1;
for j=MeshParam.Fine_Y_from:MeshParam.Fine_Y_to
   % Updated(i,j)=Updated(i,j)+1;
    F(i,j).Bz=F(i,j).Bz ...
        -F(i  ,j  ).Ex+F(i  ,j+1).Ex ...
        +F(i  ,j  ).Ey-F(i+1,j  ).EyPreserve;
end
i=MeshParam.Fine_X_to+1;
for j=MeshParam.Fine_Y_from:MeshParam.Fine_Y_to
   % Updated(i,j)=Updated(i,j)+1;
    F(i,j).Bz=F(i,j).Bz ...
        -F(i  ,j  ).Ex        +F(i  ,j+1).Ex ...
        +F(i  ,j  ).EyPreserve-F(i+1,j  ).Ey;
end
j=MeshParam.Fine_Y_to+1;
for i=MeshParam.Fine_X_from-1:(MeshParam.Fine_X_to+1)-(MeshParam.Fine_X_from-1):MeshParam.Fine_X_to+1
   % Updated(i,j)=Updated(i,j)+1;
    F(i,j).Bz=F(i,j).Bz ...
        -F(i  ,j  ).Ex+F(i  ,j+1).Ex ...
        +F(i  ,j  ).Ey-F(i+1,j  ).Ey;
end
for i=MeshParam.Fine_X_from:MeshParam.Fine_X_to
   % Updated(i,j)=Updated(i,j)+1;
    F(i,j).Bz=F(i,j).Bz ...
        -F(i  ,j  ).ExPreserve+F(i  ,j+1).Ex ...
        +F(i  ,j  ).Ey-F(i+1,j  ).Ey;
end

for j=MeshParam.Fine_Y_from-1:MeshParam.Fine_Y_to+1
    for i=MeshParam.Fine_X_to+2:MeshParam.Size_X-1
       % Updated(i,j)=Updated(i,j)+1;
        F(i,j).Bz=F(i,j).Bz ...
            -F(i  ,j  ).Ex+F(i  ,j+1).Ex ...
            +F(i  ,j  ).Ey-F(i+1,j  ).Ey;
    end
    i=MeshParam.Size_X;
   % Updated(i,j)=Updated(i,j)+1;
    F(i,j).Bz=F(i,j).Bz ...
        -F(i  ,j  ).Ex+F(i  ,j+1).Ex ...
        +F(i  ,j  ).Ey-F(1  ,j  ).Ey;
end

for j=MeshParam.Fine_Y_to+2:MeshParam.Size_Y-1
    for i=1:MeshParam.Size_X-1
       % Updated(i,j)=Updated(i,j)+1;
        F(i,j).Bz=F(i,j).Bz ...
            -F(i  ,j  ).Ex+F(i  ,j+1).Ex ...
            +F(i  ,j  ).Ey-F(i+1,j  ).Ey;
    end
    i=MeshParam.Size_X;
   % Updated(i,j)=Updated(i,j)+1;
    F(i,j).Bz=F(i,j).Bz ...
        -F(i  ,j  ).Ex+F(i  ,j+1).Ex ...
        +F(i  ,j  ).Ey-F(1  ,j  ).Ey;
end
j=MeshParam.Size_Y;
for i=1:MeshParam.Size_X-1
   % Updated(i,j)=Updated(i,j)+1;
    F(i,j).Bz=F(i,j).Bz ...
        -F(i  ,j  ).Ex+F(i  ,1  ).Ex ...
        +F(i  ,j  ).Ey-F(i+1,j  ).Ey;
end
i=MeshParam.Size_X;
% Updated(i,j)=Updated(i,j)+1;
F(i,j).Bz=F(i,j).Bz ...
    -F(i  ,j  ).Ex+F(i  ,1  ).Ex ...
    +F(i  ,j  ).Ey-F(1  ,j  ).Ey;

end
%%

function [F]=Update_Bz_FineRegion(F,MeshParam)
for j=MeshParam.Fine_Y_from:MeshParam.Fine_Y_to
    for i=MeshParam.Fine_X_from:MeshParam.Fine_X_to
%         for localjIdx=1:2
%             for localiIdx=1:2
%                 F(i,j).Bz(localiIdx,localjIdx)=F(i,j).Bz(localiIdx,localjIdx) ...
%                     -F(i  ,j            ).Ex(localiIdx                    ,localjIdx                    )...
%                     +F(i  ,j+localjIdx-1).Ex(localiIdx                    ,localjIdx+sign(1.5-localjIdx)) ...
%                     +F(i            ,j  ).Ey(localiIdx                    ,localjIdx                    )...
%                     -F(i+localiIdx-1,j  ).Ey(localiIdx+sign(1.5-localiIdx),localjIdx                    );
%             end
%         end
            localjIdx=1;
            localiIdx=1;
            F(i,j).Bz(localiIdx,localjIdx)=F(i,j).Bz(localiIdx,localjIdx) ...
                -F(i  ,j  ).Ex(localiIdx  ,localjIdx  )...
                +F(i  ,j  ).Ex(localiIdx  ,localjIdx+1) ...
                +F(i  ,j  ).Ey(localiIdx  ,localjIdx  )...
                -F(i  ,j  ).Ey(localiIdx+1,localjIdx  );
            localjIdx=1;
            localiIdx=2;
            F(i,j).Bz(localiIdx,localjIdx)=F(i,j).Bz(localiIdx,localjIdx) ...
                -F(i  ,j  ).Ex(localiIdx  ,localjIdx  )...
                +F(i  ,j  ).Ex(localiIdx  ,localjIdx+1) ...
                +F(i  ,j  ).Ey(localiIdx  ,localjIdx  )...
                -F(i+1,j  ).Ey(localiIdx-1,localjIdx  );            
            localjIdx=2;
            localiIdx=1;
            F(i,j).Bz(localiIdx,localjIdx)=F(i,j).Bz(localiIdx,localjIdx) ...
                -F(i  ,j  ).Ex(localiIdx  ,localjIdx  )...
                +F(i  ,j+1).Ex(localiIdx  ,localjIdx-1) ...
                +F(i  ,j  ).Ey(localiIdx  ,localjIdx  )...
                -F(i  ,j  ).Ey(localiIdx+1,localjIdx  );
            localjIdx=2;
            localiIdx=2;
            F(i,j).Bz(localiIdx,localjIdx)=F(i,j).Bz(localiIdx,localjIdx) ...
                -F(i  ,j  ).Ex(localiIdx  ,localjIdx  )...
                +F(i  ,j+1).Ex(localiIdx  ,localjIdx-1) ...
                +F(i  ,j  ).Ey(localiIdx  ,localjIdx  )...
                -F(i+1,j  ).Ey(localiIdx-1,localjIdx  );
    end
end
end

%%